### ISSUE TITLE
Workspaces not storing layout

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterlab/jupyterlab#10613]
## Description

I recently updated a binder tutorial with newer dependencies and it seems that workspaces no longer remember open documents/tabs and layout.

### MCRE

- `conda create -n jl-workspace -c conda-forge python=3.8 jupyterlab -y`
- `conda activate jl-workspace`
- `jupyter lab`
- Open a few notebooks and arrange them next to each other.
- Hit `File` > `Save Current Workspace As`
- Save the file
- Double click the file to open the workspace
- Note the layout has been lost

### Full context

In [this binder tutorial](https://github.com/jacobtomlinson/dask-video-tutorial-2020) we have a [jupyterlab-workspace.json](https://github.com/jacobtomlinson/dask-video-tutorial-2020/blob/master/binder/jupyterlab-workspace.json) file with a layout stored.

Then the [start](https://github.com/jacobtomlinson/dask-video-tutorial-2020/blob/828445efa3d0caa248b12be83da27e9e0de4102a/binder/start#L8) script runs `jupyter lab workspaces import binder/jupyterlab-workspace.json`.

Previously this populated the layout with Dask extension tabs, notebooks, etc. Since rebuilding today this no longer works.

## Expected behavior

Previously the open notebooks and layouts would be remembered.

## Context

- Operating System and version: macos (and binder)
- Browser and version: Firefox 89
- JupyterLab version: 3.0.16

**Comment by jtpio** [comment]
Thanks @jacobtomlinson.

I believe this was recently fixed in https://github.com/jupyterlab/jupyterlab/pull/10603, and should be available in the next 3.1 prerelease.

**Comment by jacobtomlinson** [comment]
Thanks @jtpio this is a duplicate for sure.

Does this affect all JL3 versions? I'll need to pin to something older in order to run the tutorial tomorrow.

**Comment by jtpio** [comment]
Yes it looks like it's been a regression for JupyterLab 3.0.x. For reference it was first noticed when updating the JupyterLab demo in https://github.com/jupyterlab/jupyterlab-demo/pull/102#issuecomment-756082134

**Comment by jacobtomlinson** [comment]
Thanks so much for the quick responses @jtpio. I'll pin to JL2 for now and look forward to the 3.1 release.

**Comment by jacobtomlinson** [comment]
I've had a play around with `3.1rc1` and noticed that this issue is not fully resolved. It seems to remember the layout of Jupyter core tabs like notebooks but forgets Dask plots from the dask-labextension. Do we need to change something over there to resolve this?

cc @ian-r-rose

**Comment by jacobtomlinson** [comment]
Actually sorry false alarm, I cant seem to reproduce it again.
