### ISSUE TITLE
Jupyteran 3.1.7 Table of content of notebook seems to be broken

### ISSUE THREAD

**Issue by danieltomasz** [jupyterlab/jupyterlab#10853]
After updating to Jupyterl 3.1.7 table of content with markdown headers doesn't seems to work anymore.

I check this installing jupyterlab in clean test environment.

- Operating System and version: 
- Browser and version:  latest Firefox,Chrome
- JupyterLab version:  3.1.7

**Comment by krassowski** [comment]
Hi @danieltomasz what do you mean by "doesn't seems to work anymore"?  Could you please provide reproducible steps showing what is not working? I just verified that Table of Contents works fine, but maybe you are thinking about some specific feature that I did not check - please see the GIF below:

![toc-works](https://user-images.githubusercontent.com/5832902/129609091-1aef3a22-df80-4386-92d6-c284d4a6a6ea.gif)

**Comment by danieltomasz** [comment]
It work for newly created ones
Then it doens switch to new notebooks.

![image](https://user-images.githubusercontent.com/7980381/129623580-186621e5-979d-4b4f-9e04-7738f04ab2fc.png)

![image](https://user-images.githubusercontent.com/7980381/129624289-cfe2b758-76d5-4044-884a-d7e6ed4db8ba.png)


![image](https://user-images.githubusercontent.com/7980381/129624229-2b52b474-85b3-4e5c-a4b1-b33514684793.png)

I am on PopOS 21.04 , I may send note the one that

**Comment by krassowski** [comment]
Thank you. I tried to reproduce it but failed to do so, just yet (it might be specific to certain edge cases) so it would be a great help if you could answer three more questions:

1. When the Table of Contents does not render:
   - a) are there any error messages in the [browser developer console](https://webmasters.stackexchange.com/a/77337)?
   - b) if you open the search bar in notebook (<kbd>Ctrl</kbd> + <kbd>F</kbd> when focused on a cell/notebook) does it say that the search is not available because the notebook is still loading, or does it allow you so perform search as usual?
2. Approximately how many cells does this long notebook have? Is it ~200, ~500, or ~1000, or more?
3. Do you happen to remember which was the previous version in which it worked well for you before the update?

**Comment by danieltomasz** [comment]
Output from console on notebebook that doesnt load toc
```
jlab_core.29e3fdeec73d53498432.js?v=29e3fdeec73d53498432:2 TypeError: Cannot read property 'widgets' of undefined
    at Object.p [as generate] (jlab_core.29e3fdeec73d53498432.js?v=29e3fdeec73d53498432:2)
    at ae.onUpdateRequest (jlab_core.29e3fdeec73d53498432.js?v=29e3fdeec73d53498432:2)
    at ae.e.processMessage (jlab_core.29e3fdeec73d53498432.js?v=29e3fdeec73d53498432:2)
    at b (jlab_core.29e3fdeec73d53498432.js?v=29e3fdeec73d53498432:2)
    at t (jlab_core.29e3fdeec73d53498432.js?v=29e3fdeec73d53498432:2)
    at y (jlab_core.29e3fdeec73d53498432.js?v=29e3fdeec73d53498432:2)
```
I was  earlier on 3.1.6, know even on a clean install on empty  virtualenv with  jupyterlab 3.1.6 the toc doesn't work on this specific notebook
so it may be as well issue with some dependency or the notebook itself

There is ~100 cells, with ~400 being the highest number by cell. I created this notebook before update, I had open it whole time, updated jupyterlab in the pyenv . modified notebook and then restarted the jupyterlab

I may send as zip this specific notebook through dropbox

**Comment by danieltomasz** [comment]
Yes I got this error when ctr +F
`This document is still loading. Only loaded content will appear in search results until the entire document loads.`

**Comment by krassowski** [comment]
Thank you, this is a great help - indeed this fit together with an earlier report from today with the same error message (`Cannot read property 'widgets' of undefined`) in #10840. I think we have two problems:
1. the missing check prior to one of the three `.widgets` accessors (not sure which one yet) in [`generators/notbook/index.tsx`](https://github.com/jupyterlab/jupyterlab/blob/16ad59be7abca32b5654724132902495ed9f74aa/packages/toc/src/generators/notebook/index.ts#L125-L188). I think that the issues could be in `(cell as CodeCell).outputArea.widgets` fragment which was recently introduced in #10537; maybe we are getting a cell placeholder which is missing the `widgets`?
2. The lazy "virtual" loading of notebook stalling after an uncaught error. We should be more resilient to issues like that.

**Comment by echarles** [comment]
> The lazy "virtual" loading of notebook stalling after an uncaught error. We should be more resilient to issues like that.

Are you referring to the message `This document is still loading. Only loaded content will appear in search results until the entire document loads.` or another feature that we should cover in the virtual loading? Any reproducer for this? Thx.

**Comment by krassowski** [comment]
No, I was referring to `Cannot read property 'widgets' of undefined` as it _seems_ that it interrupts notebook loading.

**Comment by echarles** [comment]
I guess any encountered exception in the notebook cell rendering will the notebook display. Wouldn't the fix you mentioned `the missing check prior to one of the three .widgets accessors ...` be enough. we can think more how to make the virtual rendering more "robust", but any prior exception stoping the rendering would anyway break the process imho.

**Comment by krassowski** [comment]
> I guess any encountered exception in the notebook cell rendering will the notebook display.

I think so too, but I do believe  should not

> we can think more how to make the virtual rendering more "robust", but any prior exception stoping the rendering would anyway break the process imho

Yes making it more robust is my point: the notebook is the crucial component and a failure in ToC subroutine should not cause all subsequent cells to stay unrendered and search function not working. If we get a try-except on a cell rendering level we could display all but faulty cells which would make debugging easier in future (allowing to narrow down the source of the problem). We could also display a pop-up with the error to report on GitHub (just ideas - I am not sure if we should go as far).

**Comment by agoose77** [comment]
> No, I was referring to `Cannot read property 'widgets' of undefined` as it _seems_ that it interrupts notebook loading.

I saw this today (similar issue to OP), so can reproduce :)

**Comment by krassowski** [comment]
@agoose77 can you repro on 3.1.10, or was it seen in an earlier release?

**Comment by agoose77** [comment]
> @agoose77 can you repro on 3.1.10, or was it seen in an earlier release?

Oh, good catch! My mistake, I'm lagging by the patch version.

**Comment by jasongrout** [comment]
> @agoose77 can you repro on 3.1.10, or was it seen in an earlier release?

@krassowski, are you implying that you think this issue can be closed and considered fixed in 3.1.10?

**Comment by Rchatru** [comment]
I have the same problem as @danieltomasz stated, (toc not displaying, same errors in the browser developer console and that loading message when pressed `Ctrl`+`F` #10840). I was in Jupyterlab version 3.1.7 and apparently the bug is fixed in v3.1.10, but it is still not available in conda, so I have downgraded to version 3.1.4, and everything works correctly again. In case it can be useful for anyone.

**Comment by krassowski** [comment]
@Rchatru the latest release 3.1.12 is available on conda-forge: https://anaconda.org/conda-forge/jupyterlab

**Comment by Rchatru** [comment]
Well, I don't know how I could have missed it, so I'll update it then. Thank you.

**Comment by fcollonval** [comment]
@krassowski what do you think should be addressed to close this one?

**Comment by krassowski** [comment]
I think we can close this one, the underlying issue was fixed. I was suggesting some improvements by adding try-catch so that notebook is more resilient to errors in less crucial plugins (like ToC) but this is indeed a conversation for another issue.

**Comment by krassowski** [comment]
It was fixed in https://github.com/jupyterlab/jupyterlab/pull/10898 and the follow-up discussion on remaining edge cases is in https://github.com/jupyterlab/jupyterlab/issues/10933
