### ISSUE TITLE
In JupyterLab 3.2.2 can't use Arrows shortcuts

### ISSUE THREAD

**Issue by sntgluca** [jupyterlab/jupyterlab#11412]
## Description
Hi all,
I apologise in advance if this was already under your radar. I searched for a similar issue but can't find any. 

In JupyterLab 3.2.2, I can't make use of Arrows to execute cell commands. 
For instance, moving between cells using ArrowUp or ArrowDown doesn't work, and I need to use the J/K keys combination instead.

The ArrowUp/ArrowDown events scroll the page instead.

## Reproduce
Open a notebook, and use ArrowUp or ArrowDown to move between existing cells, or Shift-ArrowUp/Shift-ArrowDown to select multiple cells.

The equivalent with J/K keys would work.

## Expected behavior
I expect to be able to use/modify Arrows shortcuts to execute commands such as selecting cells and activating cells.
 
In JupyterLab 3.2.1 Arrows are working well.

## Context

- Operating System and version: Tested on CentOS7 and MacOS Big Sur
- Browser and version: Chrome v 95 and Microsoft Edge Version 95 on Mac OS
- JupyterLab version: 3.2.2

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by krassowski** [comment]
Thank you for reporting! It is also tracked in https://github.com/jupyterlab/lumino/pull/256; the root issue is https://github.com/jupyterlab/lumino/pull/256 and it was already fixed in lumino and the fix should be included in the next JupyterLab release :)

**Comment by sntgluca** [comment]
Lovely, thanks!

**Comment by sntgluca** [comment]
Duplicate of  https://github.com/jupyterlab/jupyterlab-desktop/issues/320

**Comment by jasongrout** [comment]
Have we upgraded the lumino version here yet? Master dependencies still shows lumino commands 1.18, but the fix is in 1.19.

**Comment by michaelaye** [comment]
Highly annoying. Every navigation currently requires an extra Enter to go back to edit mode, just to reach other cells. :/ Can't wait for that bugfix release!

**Comment by jasongrout** [comment]
Reopening until the update to Lumino is merged (#11425).

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/in-command-mode-arrow-key-up-and-down-doesnt-change-selected-cells-but-scroll-the-page/11617/2

**Comment by jiadong93** [comment]
May I know when this can be fixed? this is a BIG issue for everyone!!!

**Comment by jasongrout** [comment]
I just released 3.2.3 on pypi that fixes this. A conda-forge release is in progress.
