### ISSUE TITLE
JupyterLab Status Bar does not work when change theme 

### ISSUE THREAD

**Issue by linlol** [jupyterlab/jupyterlab#13319]
## Description

I am sorry that I cannot post any screenshot since it is internal project...

Hi all, we upgraded jupyterlab to **3.2.6**, and some of us notice that if they change theme, for example, change dark theme to light theme, the bottom status bar disappeared.

This issue does not impact me but when I search it I found similar issue here https://github.com/dracula/jupyterlab/issues/23, which makes me try to install dracula theme, and I found that when I switch to dracula, my status bar disappeared too.

When inspecting this in devtool, I found that the internal hide() function shall not be invoked, instead, ther CSS changed which changes height and top of jp-main-statusbar element.

Our environment:

we are using jupyter in docker with base image r-notebook 3.2.6 from https://github.com/jupyter/docker-stacks with OS Ubuntu (while the OS in node server shall be RHEL7 I guess), jupyterlab is controlled by jupyterhub then.

we mount our user-setting to **Azure file share**, which means we are going to sync and load configuration.

Additionally, we are using nbresuse to display CPU and memory usage, not sure if it conflicts with status bar.

Anyone please share if there is any additional configuration works (we already keep status bar always shown but it still disappear), or if this issue is already fixed in newer version

## Reproduce

tbh not everyone among us can produce this issue, this is the most confusing part
1. install labextension nbresuse
2. install new theme maybe?
3. try switch theme across light, dark and newone

## Context

- Operating System and version: Ubuntu 22 in docker setting, and RHEL7 for node server ( I am not pretty sure)
- Browser and version: Chrome 104
- JupyterLab version: 3.2.6

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by jweill-aws** [comment]
Triage notes: This is not reproducible on 3.4.x. The 3.2.x series is not being maintained actively; would it be possible for your team to upgrade to 3.4.x for your project?

Because this issue has been fixed in 3.4.x and it's not severe enough to warrant a backport to 3.2.x, I'm going to close this issue out. Thank you for your contribution!

**Comment by linlol** [comment]
> Triage notes: This is not reproducible on 3.4.x. The 3.2.x series is not being maintained actively; would it be possible for your team to upgrade to 3.4.x for your project?
> 
> Because this issue has been fixed in 3.4.x and it's not severe enough to warrant a backport to 3.2.x, I'm going to close this issue out. Thank you for your contribution!

sorry that I am new to jupyterlab community, thanks for your help!

**Comment by quarkquartet** [comment]
I don't know whether this is the same issue, but this happens to me again on Jupyterlab-3.6.0. Are there something changed in the new version on this?

> Triage notes: This is not reproducible on 3.4.x. The 3.2.x series is not being maintained actively; would it be possible for your team to upgrade to 3.4.x for your project?
> 
> Because this issue has been fixed in 3.4.x and it's not severe enough to warrant a backport to 3.2.x, I'm going to close this issue out. Thank you for your contribution!

**Comment by JasonWeill** [comment]
@quarkquartet Can you try reproducing this using a version of JupyterLab available to launch on binder? See a list here: https://gist.github.com/jtpio/c4b6376bfbd00474b3c0d1d60fe23670

I don't see this issue in the development branch for 4.0.0. I also don't see it after launching JupyterLab 3.6.x via Binder. If you can repro this, could you please attach screen shots showing the issue? Thanks!

**Comment by quarkquartet** [comment]
> @quarkquartet Can you try reproducing this using a version of JupyterLab available to launch on binder? See a list here: https://gist.github.com/jtpio/c4b6376bfbd00474b3c0d1d60fe23670
> 
> I don't see this issue in the development branch for 4.0.0. I also don't see it after launching JupyterLab 3.6.x via Binder. If you can repro this, could you please attach screen shots showing the issue? Thanks!

Hi,

Sorry for the long silence. I tried the Binder version 3.6.x and the problem still exists.

The screenshot for light theme:
<img width="1917" alt="image" src="https://user-images.githubusercontent.com/26316540/229339093-58de7edf-be96-4f50-9aed-3c142353db8e.png">

Then I do `!pip install JLDracula`, refresh the page, choose Dracula theme in "Settings". Screenshot:
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/26316540/229339140-555702c0-6625-4471-aab4-a4e8211a4776.png">
