### ISSUE TITLE
Notebook occasionally scrolls to top

### ISSUE THREAD

**Issue by nwalters512** [jupyterlab/jupyterlab#14106]
## Description

Since updating to the `lab-3.6.1` image from 2.2.9, we've had a lot of complaints from students using RTC that the notebook is (seemingly) randomly scrolling to the top. It sounds like it may be related to autosaving, but I can't tell for sure.

## Reproduce

Unfortunately I haven't been able to reproduce this for myself yet, and from the user reports I can't tell exactly what triggers this. I'm working on getting more details, including hopefully screen recordings, from affected students. I'm filing this report in the meantime in case any maintainers might have an idea about what's happening.

## Expected behavior

I would expect notebooks to retain their scroll position unless the user explicitly scrolls them.

## Context

- Operating System and version: Docker is running on Amazon Linux 2; we're using a slightly-modified version of the `jupyter/datascience-notebook:lab-3.6.1` image (https://github.com/PrairieLearn/PrairieLearn/pull/4685/files)
- Browser and version: Various
- JupyterLab version: 3.6.1

**Comment by rob-potter** [comment]
This is happening regularly to me since turning on RTC.

**Comment by rob-potter** [comment]
Also, can provide that it's a JS error happening:
```
TypeError: Cannot read properties of undefined (reading 'model')

2jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2 
    at jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2:858602
    at k (jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2:1381838)
    at re (jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2:858581)
    at m.ie [as expandParent] (jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2:858867)
    at jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2:823603
    at g (jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2:1605476)
    at Object.c [as emit] (jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2:1605136)
    at e.emit (jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2:1603225)
    at set activeCellIndex [as activeCellIndex] (jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2:908773)
    at de.onCellRemoved (jlab_core.3e11c5239452d671150c.js?v=3e11c5239452d671150c:2:915346)```

**Comment by drorspei** [comment]
Happening to me too. I looked at this a bit, it looks like every save or so all the cells are removed and then put back. Right after the removal of the last cell there's a call to `onCellRemoved`, which asks for `activeCellIndex`. Since there are no cells - we just removed them all - it returns -1, which is set back into `activeCellIndex`, so we jump all the way to the top.

The point of the code in `onCellRemoved` seems to be that if we remove a cell above the current active cell, the current active cell index should be lowered by one, but this clashes with the logic in the collab mode of removing all cells and putting back.

(This is all guessing based on looking at the code a bit)

**Comment by rob-potter** [comment]
I cannot, our system is used for critical-path projects so we've had to disable. Looking forward to V4, to try again.

**Comment by nevercast** [comment]
My team is also experiencing this behaviour, I'll see if we can try 4.x today and let you know if the problem is still present.

Fwiw a workaround for us was to disable Autosave Documents from the Settings menu. RTC still seems to save anyway.

**Comment by ellisonbg** [comment]
Thanks, this sounds pretty severe, we should try to fix this before the 4.0 release.

**Comment by rafaelgm** [comment]
I was also experiencing this behaviour, and it stopped when I disabled collaborative mode (autosave is on)

**Comment by TwoUnderscorez** [comment]
> If possible, could you try using JupyterLab 4 alpha and see if this bug recurs? Some RTC fixes are only on the master (4.0.x) branch. 

I am on 4.0.0 and it has gotten worse.

**Comment by stevesimmons** [comment]
I am on 4.0.1 and the display jumps down several cells after executing a cell. So the newly active cell is way off the screen and I have to scroll back up again. Very painful when having to do this a hundred times a day. I'll downgrade to 3 if a fix doesn't appear soon.

**Comment by krassowski** [comment]
Can you provide reproducers?

One scenario in which I see an annoying scroll is pressing <kbd>Tab</kbd> when text in output of a cell is selected - this jumps to first cell in the notebook.

**Comment by stevesimmons** [comment]
Hi Michal @krassowski. 

My guess is there are two distinct issues: (a) several different scrolling behaviours when cells' code and/or output blocks are longer than the viewport height; (b) unexpected capturing of input focus by an different cell or the "Click to add a cell." hover thing. 

I encountered (b) with output text 900 lines long that had a strange faint watermark around 20 lines from the bottom that turned out to be the "Click to add a cell." hover indicator even though there were cells below it. No idea why it was appearing at the wrong time, but it seemed to be associated with grabbing the focus and forcing a surprising viewport scroll. I can't reproduce that easily though. I've also had the "Notebook occasionally scrolls to the top" from this issue's title, and haven't figured out any cause there.

Here's is how to reproduce (a):

- Create new Jupyter notebook
- Type `print('\n'.join(f'a{n}' for n in range(200)))` in cell 1 and `print('\n'.join(f'b{n}' for n in range(200)))` in cell 2, without executing either.
- Hit Shift + Enter in cell 1. I'd expect to see the tail end of cell 1's output (lines a119-a199) and that cell 2 has the focus. But the viewport stays in the same place, with output lines a0-a78 visible. The focus has moved to cell 2, which is now off the bottom of the screen so I can't see which cell has the blue highlight for next input or tell whether I am in command mode or editing cell 2. Jupyter has placed me in command mode.
-  Now hit Shift + Enter in cell 2. The viewport shows output lines b121 to b199 (whereas in the previous case it was a0-a78), with a new cell 3 in edit mode visible at the bottom of the screen. I'm not sure why before I ended in command mode and now am in edit mode.
- This inconsistency in cmd vs edit mode is potentially dangerous because if JupyterLab is in edit mode, the first keystroke scrolls the viewport so the code cell is in view. But if in command mode, the keystrokes execute commands without scrolling. So I can accidentally type `dd`, for example (starting to type `def ...` for instance, and trying `d` again when I see nothing on the screen), and not be aware I've deleted the code cell below the bottom of the screen.
- There's also an inconsistency in arrow key behaviour depending on whether in command or edit mode. In edit mode, up and down arrows move through a cell's code area, with the viewport shifting to keep the region with the cursor in view. So you can scroll up repeatedly and always know where you are. Whereas in command mode, the up and down arrows seem to mostly scroll to keep the bottom of the output area in view, which keeps the code hidden if there is more than a screenful of output. If you then start typing, the code area doesn't scroll into view when it gets input focus, but only when the next character is typed. This is confusing and again potentially dangerous, because you can't see what mode you are in and therefore may not be aware what will happen as the result of typing the next character.
- Also if you keep hitting up, at the top, JupyterLab will stop at the bottom of the first cell's output. If that cell's output is long, you can't see you are back at the top, and more up arrows never makes its code visible. 
- And sometimes, scrolling using the arrow keys has a slightly different behaviour where it brings me to somewhere in the middle of the cell's output. This seems dependent on the scroll position at the start, and maybe whether there is a cell below or now and whether it or its output is longer than one screen.


My suggestion to make these behaviours more predictable is:

1. Ensure that after hitting any of Shift/Ctrl/Alt + Enter, at least some of the now active cell's code area is visible, so the user can see the blue bar and tell if the code area has started editing or if Jupyter is still in command mode.
2. If the edit area ever becomes active while not visible, the viewport is scrolled so it is immediately made visible. No more waiting for the second keystroke (after the first which made it active). 
3. Scrolling up will always end at the top of the first cell's code area. Currently it mostly stops at the bottom of the first cell's output area.
4. If a cell is longer than a screen, then scrolling up shows the top of the code area, and scrolling down shows the bottom of the output area. Ideally these would also show the bottom couple of lines of the previous cell when scrolling up and the first couple of lines of the next cell when scrolling down. That means when scrolling quickly with the arrow keys, the screen always shows some context of a neighbouring cell and the `[nn]` input or output cell number indicator.

**Comment by TwoUnderscorez** [comment]
@stevesimmons correct me if I'm wrong, but I don't think that what you're describing is what @nwalters512 and I are experiencing.

@JasonWeill @krassowski Here is a video of what I'm talking about and the mentioned notebook. Hopefully you can reproduce this behavior. 

https://github.com/jupyterlab/jupyterlab/assets/25303006/99c1610c-56de-4594-bb5a-c0f4afbd4aef
[numanal.zip](https://github.com/jupyterlab/jupyterlab/files/11643568/numanal.zip)

Also JS console log:
[console-export-2023-6-3_22-29-21.txt](https://github.com/jupyterlab/jupyterlab/files/11643591/console-export-2023-6-3_22-29-21.txt)

And here is my configuration:
[jupyterhub.zip](https://github.com/jupyterlab/jupyterlab/files/11643570/jupyterhub.zip)

**Comment by eul94458** [comment]
Can confirm this bug. It is very confusing since who knows what trigger that.

**Comment by krassowski** [comment]
This could be an interaction of tab focus problem which is getting fixed in #14115 with windowed rendering.

**Comment by krassowski** [comment]
Related to #13343.

**Comment by jakeau** [comment]
This may help I have a habit of hitting cntrl + s with RTC on with auto save on and off, it happens more often then not when I press cntr+s

**Comment by MoritzWeber0** [comment]
I can confirm that the bug does still exist in jupyterlab version 4.0.5. 
According to my observations, this always happens when saving. Sometimes the save doesn't seem to work properly, then all changes since the last save are lost. Also, the cursor jumps to the first cell.

**Comment by ellisonbg** [comment]
Thanks for the update, @andrii-i can you investigate?

**Comment by echuber2** [comment]
> I was also experiencing this behaviour, and it stopped when I disabled collaborative mode (autosave is on)

This comment in particular makes me wonder if the issue is related to collaborative syncing features. It sounds like those were introduced in v3.1.0: https://github.com/jupyterlab/jupyterlab/releases/tag/v3.1.0 If I understand correctly from the comments on another issue (https://github.com/jupyterlab/jupyterlab/issues/15083), OP @nwalters512 ended up rolling back to v2.x specifically because it didn't have this scrolling issue. So perhaps someone could bisect on the v3.x releases.

**Comment by hbcarlos** [comment]
Hi everyone.

I have spent a bit of time debugging this issue, and in my opinion, we have three different issues. Here are my thoughts:

1. Comment https://github.com/jupyterlab/jupyterlab/issues/14106#issuecomment-1574273088 by @krassowski
> One scenario in which I see an annoying scroll is pressing Tab when text in output of a cell is selected - this jumps to first cell in the notebook.

There's not much to say here; it is happening, is easy to reproduce, and is annoying.

2. Comment https://github.com/jupyterlab/jupyterlab/issues/14106#issuecomment-1574991785 by @stevesimmons
> Create new Jupyter notebook
>
> Type print('\n'.join(f'a{n}' for n in range(200))) in cell 1 and print('\n'.join(f'b{n}' for n in range(200))) in cell 2, without executing either.
> 
> Hit Shift + Enter in cell 1. I'd expect to see the tail end of cell 1's output (lines a119-a199) and that cell 2 has the focus. But the viewport stays in the same place, with output lines a0-a78 visible. The focus has moved to cell 2, which is now off the bottom of the screen so I can't see which cell has the blue highlight for next input or tell whether I am in command mode or editing cell 2. Jupyter has placed me i[n comman](http://mode.now/)d mode.
> 
>Now hit Shift + Enter in cell 2. The viewport shows output lines b121 to b199 (whereas in the previous case it was a0-a78), with a new cell 3 in edit mode visible at the bottom of the screen. I'm not sure why before I ended in command mode and now am in edit mode.

This happens because the cursor moves to the next cell in command mode when executing a cell, so the viewport doesn't move. Instead, when running the last cell, we create a new one at the end and set the focus in the new cell in edit mode so the viewport scrolls to that cell.

To fix this, we would need to review the scroll/focus behavior of three different parts of the notebook to make them work smoothly together. When in edit mode, in command mode, and the transitions between them. In addition, we should look into the new feature that allows closing/shorting the outputs to behave similarly to the classic notebook.

3. Comment https://github.com/jupyterlab/jupyterlab/issues/14106#issuecomment-1575160899 by @TwoUnderscorez

From the resources @TwoUnderscorez shared, they use JupyterLab v4 with multiple extensions from JupyterLab v3. There is one extension in particular that could cause this issue, JupyterLab-LSP. This extension doesn't support JupyterLab v4. In addition, we can see in the video that the first jump comes after selecting a completion, and their logs show multiple LSP errors.

Nevertheless, from what I see in that video, we might have an issue with the autosave from RTC. Every time the cursor jumps to the first cell, the notebook's content gets restored to the last saved state. Looking carefully at the video, we can see that the cursor jumps back to the first cell when the user types something while the backend saves the document. Immediately after jumping, the "dirty" indicator is cleared, and the content gets restored to the last saved state.

In my opinion, we might have a race condition with the autosaving action in the backend.

**Comment by MoritzWeber0** [comment]
> > I can confirm that the bug does still exist in jupyterlab version 4.0.5.
> > According to my observations, this always happens when saving. Sometimes the save doesn't seem to work properly, then all changes since the last save are lost. Also, the cursor jumps to the first cell.
> 
> @MoritzWeber0 could you please check if you are getting this problem only with RTC on?

We experienced the issue after the the installation of `jupyter-collaboration`. Before that, we never observed the problem, so I strongly assume that it is related to RTC.

**Comment by andrii-i** [comment]
Thank you @MoritzWeber0

**Comment by krassowski** [comment]
@hbcarlos there is a related issue:
- #14878

I am also experiencing a fourth scenario which is I believe is related to ToC and basically prevents scrolling past a cell at all. It is difficult to isolate but if I manage, I will post a reporducer.

**Comment by hbcarlos** [comment]
Thanks @krassowski !

**Comment by krassowski** [comment]
Here it is @hbcarlos:

1. Use Firefox or Chrome latest or stable (I reproduced across multiple versions)
2. Go to JupyterLab settings, change `Windowing mode` to `full`
3. Create a notebook with ~200 empty cells
4. Convert a cell into markdown and type  `# test` creating a heading
5. In a code cell below enter `print('\n'.join(str(i) for i in range(100)))` and execute
6. Perform the motion as on the screencast:
    ![no-cel-active-all-fine](https://github.com/jupyterlab/jupyterlab/assets/5832902/39fc2edc-d104-4151-be54-c48de44a1c3e)
7. See that all is good
8. Enter the markdown cell with a heading
9. Try to repeat the motion as in point (6)
10. See annoying, disorienting jump which makes me disable the `full` windowing mode:
   in attempt one it took me up to the selected cell and then back down; I experienced a very distressing circumstance when I was stack and unable to navigate past a cell by scrolling up at all but it is not as reliably reproducible
   ![jump-back](https://github.com/jupyterlab/jupyterlab/assets/5832902/1af0dca0-1bac-44b9-97a3-413d380ce762)
   in take two it just jumped over the output of the cell preventing me from reading the lines in between
   ![jump-back-take-2](https://github.com/jupyterlab/jupyterlab/assets/5832902/9ea778dd-6fe3-4057-891c-cc29f425d8e5)


CC @afshin

I though that ToC is to blame because it does trigger this behaviour because when you click on a cell heading it enters the cell into markdown mode (which is super annoying too and I believe someone else reported it but cannot find the issue).

**Comment by krassowski** [comment]
Also, there is another case of annoying scrolling on splitting cells:
- #14728

**Comment by krassowski** [comment]
> I though that ToC is to blame because it does trigger this behaviour because when you click on a cell heading it enters the cell into markdown mode (which is super annoying too and I believe someone else reported it but cannot find the issue).

Well, these were just numerous comments not a standalone issue - I created one collating the two comments that I was able to find easily: https://github.com/jupyterlab/jupyterlab/issues/15228

**Comment by mszinte** [comment]
Dear all,
Is their any update on this problem that unfortunately I also encounter on my jupyter lab hub making my working day really hard.
Thanks,

**Comment by krassowski** [comment]
@mszinte it depends which specific problem of many different behaviours described in this thread you are experiencing.
1) Scroll on <kbd>Tab</kbd> when output is focused should be fixed once https://github.com/jupyterlab/jupyterlab/pull/14115 is merged
2) The problematic behaviours that @stevesimmons described will likely be solved by https://github.com/jupyterlab/jupyterlab/pull/15288 and https://github.com/jupyterlab/jupyterlab/pull/15286
3) The issue described by @TwoUnderscorez [here](https://github.com/jupyterlab/jupyterlab/issues/14106#issuecomment-1575160899) needs isolation so that we have a minimum reproducible example/can understand what conditions are necessary to trigger it
4) I do not know if anyone is working on the behaviour described [in my comment above](https://github.com/jupyterlab/jupyterlab/issues/14106#issuecomment-1749112997) but I would be happy to work on it (resources/time permitting).

It would be valuable to know which of these behaviours you are experiencing and whether you have windowing mode set to `full` in Notebook settings or not.

**Comment by mszinte** [comment]
Hi @krassowski ,

Thanks for your quick reply. 
My problem is not corresponding the case 1/ or 2/, it does look like case 3/.

I tried to reproduce your case but it doesn't create the problem at least not systematically (see below).

In my case, since a recent update there are at some random instants (really I don't know how to reproduce but they are frequent) a jump to the first cell together with a return to a time of about 2 seconds before the jump in the cell that I was using. In other words the last piece of code I wrote disappears and the prompt jumps to the first cell. Also if the code of a cell is running during this error, the code is still executed but the status stays as busy infinitely. 

Also my notebook windowing mode is set to `difer`.

Best,

**Comment by krassowski** [comment]
@mszinte can you provide output of: `jupyter --version` and `jupyter labextension list` so that we can triangulate?

**Comment by mszinte** [comment]
Yes, here are these information.

`jupyter --version`

`Selected Jupyter core packages...
IPython          : 8.14.0
ipykernel        : 6.25.1
ipywidgets       : 8.1.1
jupyter_client   : 8.3.0
jupyter_core     : 5.3.1
jupyter_server   : 2.7.2
jupyterlab       : 4.0.7
nbclient         : 0.8.0
nbconvert        : 7.7.4
nbformat         : 5.9.2
notebook         : 7.0.2
qtconsole        : not installed
traitlets        : 5.9.0`


`jupyter labextension list`

`JupyterLab v4.0.7
/opt/jupyterlab/venv/share/jupyter/labextensions
        jupyterlab-plotly v5.17.0 enabled  X
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)
        @jupyter/collaboration-extension v1.0.1 enabled OK (python, jupyter_collaboration)
        @jupyter-notebook/lab-extension v7.0.2 enabled OK


   The following extensions are outdated:
        jupyterlab-plotly
        jupyterlab_pygments

   Consider checking if an update is available for these packages.

Other labextensions (built into JupyterLab)
   app dir: /opt/jupyterlab/venv/share/jupyter/lab
        @plotly/dash-jupyterlab v0.4.3 enabled  X
        jupyterlab-dash v0.4.2 enabled  X

   The following extensions are outdated:
        @plotly/dash-jupyterlab
        jupyterlab-dash

   Consider checking if an update is available for these packages.



Disabled extensions:
    @jupyterlab/filebrowser-extension:defaultFileBrowser`

**Comment by jordanmorriswaybeyond** [comment]
I can reproduce this by adding a cell near the bottom of a long notebook, using the b hotkey. It appears to be jumping to a keyword which was sitting in my (closed) search box, from a term I was searching earlier. Jupyter 7.0.5, Edge browser.

**Comment by krassowski** [comment]
@jordanmorriswaybeyond thanks for the comment, this is tracked in https://github.com/jupyterlab/jupyterlab/issues/14871

**Comment by derycck** [comment]
> The jumping to the top stopped after I re-opened my search box (CTRL+F) and deleted the search term out of it. Note this was the jupyter search box, as opposed to browser find-in-page.

This quickfix works great here. The bugs is over. Thanks for the tip.

**Comment by GregS83** [comment]
Hi, the bug hasn't been solved. I'm on a mac with the latest version of Jupyter Notebook and it still sporadically scrolls to the  top when I'm typing the code. I have nothing in the find box.

**Comment by mszinte** [comment]
Hi, I'm not certain of the direct link but when I switched off the collaborative mode of my JupyterLab the problem stopped.
`jupyter labextension disable @jupyter/collaboration-extension`

**Comment by kl00z** [comment]
I also post the requested commands on an installation in which I do **not** see this issue (3/)

Output from ` jupyter --version`

```
IPython          : 8.5.0
ipykernel        : 6.16.0
ipywidgets       : 8.0.2
jupyter_client   : 7.3.5
jupyter_core     : 4.11.1
jupyter_server   : 1.19.1
jupyterlab       : 3.4.7
nbclient         : 0.6.8
nbconvert        : 7.1.0
nbformat         : 5.6.1
notebook         : 6.4.12
qtconsole        : not installed
traitlets        : 5.4.0
```

Output from `jupyter labextension list`

```
JupyterLab v3.4.7
/opt/miniconda3/envs/mlam_gpu/share/jupyter/labextensions
        jupyter-matplotlib v0.11.2 enabled OK
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v5.0.3 enabled OK (python, jupyterlab_widgets)
```

Best,

**Comment by erkin98** [comment]
Go to Notebook (notebook opening with IDocumentManager.openOrReveal)
Click on insert cell button
Auto Scroll down happens
that does not happens when notebook opening with IDocumentManager.open
Jupyterlab version is 4.1.5, I've tested 4.2 as well

**Comment by ndamulelonemakh** [comment]
Ahhh...I have just decided to stop using sagemaker due to this! I will happily fallback to vscode. I tried to be understanding , but after a while it just gets frustrating especially since the navigation by headings on the sections outline does not work as well, so I have to manually drag the scrollbar after every few minutes

**Comment by andrii-i** [comment]
Hi @ndamulelonemakh. I've noticed your comment and was interested to learn more about your problem and look into solving it. Could you please advise if you are using Amazon SageMaker Studio Classic (JupyterLab 3) or Amazon SageMaker Studio (JupyterLab 4)?

**Comment by andrii-i** [comment]
Everyone, please note that issue #16144 is not connected to this issue / "notebook occasionally scrolls to top" unwanted behavior. 

@erkin98 I looked at issue #16144 you created while I was trying to troubleshoot this issue. Auto scroll described and shown in #16144 is a standard / expected behavior during the creation of a new cell. Viewport is expected to move / scroll to automatically show the new cell including during the creation of a new cell via "Insert a cell below (B)" as shown on video. If you find this default behavior problematic, it would make sense to open an issue about "Auto Scroll on new cell creation" to for example discuss a possibility of making such a behavior optional.

**Comment by andrii-i** [comment]
Hi @ndamulelonemakh. I've noticed your comment and was interested to learn more about your problem and look into solving it. Could you please advise if you are using SageMaker Studio Classic (JupyterLab 3) or SageMaker Studio (JupyterLab 4)?

**Comment by ndamulelonemakh** [comment]
Sagemaker studio. So when I'm typing something in a cell, it intermittently moves the cursor to the first cell. The frequency seens to slightly increase over time

**Comment by andrii-i** [comment]
Thank you for the feedback @ndamulelonemakh. Could you please share an anonymized version of a notebook you are having this problem in?

**Comment by andrii-i** [comment]
Our team spent last week investigating "scrolls to top" bug and trying to reproduce it. We tried and were not able to reproduce it in JupyterLab 4, Notebook 7, and nbclassic with and without real-time collaboration enabled. It seems that the behavior is not present in the latest versions or is extremely rare.

We will keep tracking this thread and will spend more time focusing on this bug if there would be more occurrences of the "scrolls to top" bug reported or if/when someone would be able to put together and share an example notebook that reproduces the problem.

**Comment by geauxtigers** [comment]
I am having the same issue and it has persisted through several versions.  These are my current versions:

Notebook ['7.2.1']
Lab ['4.2.2']

I think I may have somewhat isolated the issue.  I attached a video showing the behavior (it may be blocked from attaching on this computer).  But nonetheless, the notebook seems to only scroll to the top when the next cell or end of notebook are visible at the bottom of the screen when I submit the cell (Ctrl-Enter).  I also added some cells after the first cell and the scroll seems to happen even if the output of cell 1 is visible.  I hope this helps.

**Comment by andrii-i** [comment]
@geauxtigers thank you for sharing. I'm having a hard time reproducing this based on the text description. If you could attach the video you are mentioning it would really help. If you could also create an example notebook showcasing the problem and share it (for example via https://gist.github.com/), it would really help as well.

**Comment by geauxtigers** [comment]
Thanks @andrii-i ... Here is the video showing just an example notebook, mostly with spaces to get the cell larger than the height of the screen.  I place the cursor in multiple locations and submit the cell with Ctrl+Enter.  When the bottom of the notebook is within the viewable area and the cell is submitted, the notebook scrolls to the top of the cell.  In my instance it scrolls to the top of the cell that was executed and not the top of the notebook.

https://github.com/jupyterlab/jupyterlab/assets/8951542/61bde2ac-2ce8-4dbd-bfe6-7ca0040558d1

https://gist.github.com/geauxtigers/f5ec3bfeb00f529e77ba9f314d3fed4d

**Comment by krassowski** [comment]
@geauxtigers thank you for the reproducer - I can reproduce it following your steps; since this is not about scrolling the to the top of the notebook, but about scrolling to the top of a cell I extracted it to a new issue: https://github.com/jupyterlab/jupyterlab/issues/16505

**Comment by andrii-i** [comment]
Thank you @geauxtigers for quick feedback, video, and example notebook. Let's continue discussion on "when a long cell is executed, notebook scrolls to the top of this cell" in #16505.

**Comment by angelopeixoto** [comment]
> Thanks [@andrii-i](https://github.com/andrii-i) ... Here is the video showing just an example notebook, mostly with spaces to get the cell larger than the height of the screen. I place the cursor in multiple locations and submit the cell with Ctrl+Enter. When the bottom of the notebook is within the viewable area and the cell is submitted, the notebook scrolls to the top of the cell. In my instance it scrolls to the top of the cell that was executed and not the top of the notebook.
> 
>  jupyter_scroll.mp4 
> https://gist.github.com/geauxtigers/f5ec3bfeb00f529e77ba9f314d3fed4d

Disabling the auto-sync feature on the OneDrive GUI and/or Dropbox eliminated the problem. The files in question resided in the folder configured for automatic, real-time synchronization.
If you are using one of these programs, please try disabling or closing it temporarily to check if the problem continues.

**Comment by krassowski** [comment]
> Since updating to the lab-3.6.1 image from 2.2.9, we've had a lot of complaints from students using RTC that the notebook is (seemingly) randomly scrolling to the top. It sounds like it may be related to autosaving, but I can't tell for sure

Addressing the original issue, I can confirm that there is a jump to the top, which is not related to virtual rendering but strictly to RTC. This indeed is related to saving the notebooks - when notebook is saved via REST API or modified on the disk, the widgets reload and scroll state, along with the widget state gets lost. This is now tracked on implementation level in:

- https://github.com/jupyterlab/jupyter-collaboration/issues/510
- https://github.com/jupyterlab/jupyter-collaboration/issues/509
- https://github.com/jupyterlab/jupyterlab/issues/18100

**Comment by krassowski** [comment]
A fix for the first issue was released in `jupyter-collaboration` [`v4.1.2`](https://github.com/jupyterlab/jupyter-collaboration/releases/tag/v4.1.2)

**Comment by krassowski** [comment]
A fix for scroll to top on `touch` and smaller out-of-band changes (as long as they do not swap cell IDs) was released in `jupyter-ydoc` [`v3.2.0`](https://github.com/jupyter-server/jupyter_ydoc/releases/tag/v3.2.0).

I am going to close this issue as resolved, as I believe it should no longer happen with stock JupyterLab with `jupyter-collaboration` and `jupyter-ydoc` in the latest versions. If you do encounter it, please comment here or open a new issue if comments are locked.
