### ISSUE TITLE
Kernel error after pip install jupyterlab

### ISSUE THREAD

**Issue by nigue3025** [jupyterlab/jupyterlab#15301]
HI,
Today (Oct.25,2023) I just pip install jupyterlab.

## Description
After opening the browser, it failed to start any .ipynb files with "Error Starting Kernel" alerted as follows no matter in Ubuntu20.0.4 and Windows10 OS:

            File ".../venv/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
            ...
              File ".../venv/lib/python3.10/site-packages/jupyter_client/multikernelmanager.py", line 226, in update_env
                self._kernels[kernel_id].update_env(env)
            TypeError: KernelManager.update_env() takes 1 positional argument but 2 were given

After checking pip list, several modules just updated today as follows:

Babel==2.13.1
ipykernel==6.26.0
jupyter_client==8.5.0
jupyter_server==2.9.0
traitlets==5.12.0

Also, I found out that ipykernel ==6.26.0 just released today (Oct.25., 2023)

## Reproduce
I tried to restore the above module version back to the previous versions and rebuilt my virtual venv by as follows :

Babel==2.13.0
ipykernel==6.25.2
jupyter_client==8.4.0
jupyter_server==2.8.0
traitlets==5.11.2

Now all the .ipynb files can work now.

I am wondering if there is something wrong on the above modules with newer version.

Thanks

**Comment by 1e100** [comment]
Same here, FWIW. In my case I'm installing it in Docker. Could provide a dockerfile if that helps.

**Comment by dove-young** [comment]
Similar to me. In my case this is `Python 3.11.2` on RHEL 8.x. 
```
[root@st2]# jupyter lab --allow-root --no-browser
[I 2023-10-25 00:15:36.659 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-10-25 00:15:36.671 ServerApp] Package jupyter_lsp took 0.0114s to import
[W 2023-10-25 00:15:36.671 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will
 be deprecated in future releases of Jupyter Server.
[W 2023-10-25 00:15:36.671 ServerApp] jupyter_server_fileid | error adding extension (enabled: True): The module 'jupyter_server_fileid' could not be found (No module named 'jupyter_server_fileid'). Are you sure the extension i
s installed?
    Traceback (most recent call last):
      File "/root/jupyter/virtualenv/llma_index/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/jupyter/virtualenv/llma_index/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/root/jupyter/virtualenv/llma_index/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'jupyter_server_fileid' could not be found (No module named 'jupyter_server_fileid'). Are you sure the extension is installed?
[I 2023-10-25 00:15:36.676 ServerApp] Package jupyter_server_terminals took 0.0041s to import
[W 2023-10-25 00:15:36.676 ServerApp] jupyter_server_ydoc | error adding extension (enabled: True): The module 'jupyter_server_ydoc' could not be found (No module named 'jupyter_server_ydoc'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/root/jupyter/virtualenv/llma_index/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/jupyter/virtualenv/llma_index/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/root/jupyter/virtualenv/llma_index/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'jupyter_server_ydoc' could not be found (No module named 'jupyter_server_ydoc'). Are you sure the extension is installed?
[W 2023-10-25 00:15:36.677 ServerApp] nbclassic | error adding extension (enabled: True): The module 'nbclassic' could not be found (No module named 'nbclassic'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/root/jupyter/virtualenv/llma_index/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
```

**Comment by SteffenBauer** [comment]
As a quickfix, I managed to fix this by downgrading just the `jupyter_server` package from 2.9.0 to 2.8.0.

**Comment by dove-young** [comment]
> As a quickfix, I managed to fix this by downgrading just the jupyter_server package from 2.9.0 to 2.8.0.

@SteffenBauer cool. it works for me.

**Comment by jans-code** [comment]
I am having that same error with all my custom kernels.

```
TypeError: KernelManager.update_env() takes 1 positional argument but 2 were given
```

I downgraded `jupyter_client` to `8.4.0` and all works again.

**Comment by MirrorAzure** [comment]
Looks like this problem lies in `jupyter_client\multikernelmanager.py`
```
    def update_env(self, *, kernel_id: str, env: t.Dict[str, str]) -> None:
        """
        Allow to update the environment of the given kernel.

        Forward the update env request to the corresponding kernel.

        .. version-added: 8.5
        """
        if kernel_id in self:
            self._kernels[kernel_id].update_env(env)
```
`update_env` takes `env` as keyword argument, but tries to pass it like positional.
Changing it to `self._kernels[kernel_id].update_env(env=env)` should fix it.

**Comment by krassowski** [comment]
Thank you all for reporting, this is an error in the latest release of jupyter-server (2.9.0): https://github.com/jupyter-server/jupyter_server/issues/1345

Hopefully it will get fixed soon, for now I would recommend downgrading to jupyter-server 2.8.0.

**Comment by nigue3025** [comment]
Today (Oct.26,2023) I just pip installed jupyterlab again and found out that jupyter_server upgraded to 2.9.1.
No kernel error occurs as selecting a kernel for a ipynb file
Appreciate for your help!

**Comment by jevad** [comment]
I'm using jupyter_server 2.10.0, and the bug is still there.

**Comment by krassowski** [comment]
@jevad what version of jupyter-client do you have installed?

**Comment by jevad** [comment]
Thanks!   Here is another data point for you:  jupyter_server 2.10 and jupyter_client 8.6.0 is working for me.
