### ISSUE TITLE
Erratic Scroll Jump just when scrolling

### ISSUE THREAD

**Issue by burnpanck** [jupyterlab/jupyterlab#15968]
## Description

Recently, in the standalone Jupyter notebook mode, I started to occasionally observe a scroll glitch.

https://github.com/jupyterlab/jupyterlab/assets/1310437/7b74fadf-7a70-4124-8807-1b1452eec86a

## Reproduce

It is unfortunately unclear what exactly is required to trigger this issue initially.
1. My notebook is relatively long.
2. The cell re-writes some text (using `display.clear_output(wait=True)`, which ultimately fails with an exception.
3. After the cell stopped executing, start to scroll upwards, from the cell output towards the cell content
4. At some point roughly when the top of the just executed cell becomes visible, the view suddenly jumps to align the top of the *next* cell with window
5. You can do this several times
6. If you bring another browser window into foreground and then go back, the glitch is sometimes gone.

## Expected behavior

Normal scroll.

## Context

- Operating System and version: macOS 14.4
- Browser and version: Chrome 122.0.6261.112 
- JupyterLab version: 7.1.1
- Windowing mode: `defer`

### Related issues:
- #14878 -> suggests windowing mode `full` -> layout is completely broken in this mode for me (cells expand out of the right of the window due to long lines)
- #15693 -> appears to be connected with notebook "actions". no "action" is triggering the glitch here, just scrolling on it's own.

**Comment by JasonWeill** [comment]
Do you have JupyterLab installed? If so, which version are you using, and do you see this same behavior in Lab?

 #14106 concerns the scroll bar jumping to the top, but that's not what you're reporting here.

**Comment by burnpanck** [comment]
I was able to reproduce the same behaviour in JupyterLab, basically on first try on a notebook cell that had shown the same behaviour right before in the classical notebook interface.

**Comment by burnpanck** [comment]
A few more random observations:
 - There is no message on the developer console.
 - It seems to be associated with a specific cell in the notebook - scrolling over other cells does not trigger it.
 - Not all executions of that particular cell seem to cause that behaviour.
 - It appears to me that it happens more often when that cell executes for a long time, repeatedly clearing the cell output before failing with an exception
 - The cell input is about two screens high, and so is the output. In this particular case, there is maybe just one more screen of cells above, but not much more (it's a different notebook than the one from the screencast above, though similar cell).
 - Once that cell entered that "glitching mode", it's pretty persistent (for a while). You can sometimes scroll over it (by scrolling very fast), but even afterwards, scrolling down and up again still triggers it.
 - Re-executing the cell seems to recover out of the "glitching mode".
 - Re-loading the jupyter lab interface (i.e. browser reload) also recovers out of the "glitching mode"

**Comment by burnpanck** [comment]
Is there anything I can do to help resolve or at least mitigate this issue. It still happens regularly to me, and it is extremely disorienting and annoying, to the point that I am putting back all work involving a jupyter notebook.

**Comment by burnpanck** [comment]
Unfortunately, the issue seems to persist. This was with `jupyterlab==4.2.0a2` and `notebook==7.1.1`, which, officially, are incompatible. Obviously, I did a restart of the server followed by a hard reload of the browser window of the affected notebook.

**Comment by burnpanck** [comment]
I just found the older bug report #15795, which, from the description, matches the behaviour I see.

**Comment by krassowski** [comment]
> This was with jupyterlab==4.2.0a2 and notebook==7.1.1, which, officially, are incompatible

I am confused, did you see the behaviour in Notebook or in JupyterLab interface?

> I just found the older bug report https://github.com/jupyterlab/jupyterlab/issues/15795, which, from the description, matches the behaviour I see.

The author of https://github.com/jupyterlab/jupyterlab/issues/15795 says that they cannot reproduce this when switching to `full` windowing mode. In JupyterLab 4.2.0b0 it is on by default but you can also change it in Settings Editor → Notebook → Windowing mode. Do you still see this in 4.2.0beta0?

Also, are you using a trackpad or a mouse?

**Comment by burnpanck** [comment]
I mostly use the notebook interface, but I [previously](https://github.com/jupyterlab/jupyterlab/issues/15968#issuecomment-1992233447) was able to reproduce it in juptyterlab as-well. I was under the assumption that it is therefore a manifestation of a bug in the shared code-base, and thus observation in either interface counts as confirmation. This may have been a wrong assumption though. The comment you referred to above was in fact an observation from the notebook interface.

**Comment by tillahoffmann** [comment]
I observe similar behavior in Jupyter Lab with Safari on macOS 14.4. See below for installed versions.

```bash
$ python --version
Python 3.10.9
$ pip freeze | grep jupyter
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.9.1
jupyter-lsp==2.2.4
jupyter_client==8.6.1
jupyter_core==5.7.2
jupyter_server==2.13.0
jupyter_server_terminals==0.5.3
jupyterlab==4.1.4
jupyterlab_pygments==0.3.0
jupyterlab_server==2.25.4
jupyterlab_widgets==3.0.10
```

I'll update Jupyter Lab to the most recent version to double check it's not resolved in a recent release.

**Comment by burnpanck** [comment]
I just reproduced it again in JupyterLab 4.2.0b1 (i.e. lab interface), after observing it in Jupyter Notebook 7.2.0a0. "windowing mode" was set to `defer`. I'm now switching to `none`, in the hope of an improvement of the situation.

**Comment by burnpanck** [comment]
Does that "windowing mode" only affect the lab interface, or also the classic notebook interface? In classic notebook, same behaviour with `none` even after a hard reload.

**Comment by burnpanck** [comment]
Also reproduced with jupyter lab in `none` mode.

**Comment by burnpanck** [comment]
Same with `full`.

**Comment by burnpanck** [comment]
I see that @jtpio did merge two changes on the release candidate branch (in `7.2.0b1`, the one that I tested last) that may potentially interact with this (i.e. if I read the description correctly, basically inactivating the windowing mode selector). If windowing-mode `full` was indeed a workaround for this issue before as suggested by @krassowski in #15693, then that commit actually worsened the situation here.

Unfortunately, this issue is extremely frustrating, because it completely prevents the user from navigating a notebook, with the only remedy to re-load the notebook from disk or re-executing the offending cell (if you can still reach there). It is happening erratically with no clear pattern visible except that it seems to be triggered by a cell output - though both "instant" cells and long-running ones.

**Comment by jtpio** [comment]
> If windowing-mode `full` was indeed a workaround for this issue

Was it? Previously it was more the opposite, with the `full` windowing mode causing more scrolling issues than `defer` (https://github.com/jupyterlab/jupyterlab/issues/13343).

Otherwise yes Notebook currently still has issues with the `full` windowing mode, which hopefully will be fixed at some point (https://github.com/jupyter/notebook/issues/7318).

So https://github.com/jupyter/notebook/pull/7335 forces to `defer` for now, but this should not change the windowing mode in JupyterLab anymore like it used to when changing the settings.

**Comment by burnpanck** [comment]
I never confirmed `full` being a workaround. It was suggested by @krassowski that #15288 fixed #14878 and potentially #15693 which may be related (at least they are scrolling-related issues), but the fix was only done for `full`. When I first opened this issue, I did not try `full` for an extended period of time exactly because of https://github.com/jupyter/notebook/issues/7318, which is even worse than this issue here and at that time I was under a lot of pressure from my paid work. So I did not exhaustively test windowing modes before `7.2.0b1`. But I can roll back to 7.2.0b0 if you think it's reasonable, switch to `full` and see if I still observe the issue.

**Comment by burnpanck** [comment]
> So https://github.com/jupyter/notebook/pull/7335 forces to `defer` for now, but this should not change the windowing mode in JupyterLab anymore like it used to when changing the settings.

Maybe I still don't understand well enough how the notebook interface in the lab interface relates to the classic notebook interface. I do prefer the latter, so I only use the lab interface to help debug this issue. My testing on `7.2.0b1` basically involved using the "Notebook settings" section in the lab settings interface to (attempt to) change the windowing mode, then working with a notebook until the issue next appears - both in the classic interface and the lab interface. If I understand correctly, with `7.2.0b1`, this did in fact effectively change the windowing mode for the lab interface but not in the classic notebook interface? Since I observed the scrolling issue with all three settings in both interfaces, it appears that it is unlikely that `full` fixes anything in this regard.

**Comment by burnpanck** [comment]
It appears that issue is still present in that `7.2.0b2` from the `check_release` CI artefact. I just encountered another case of scroll jump. Here is what I observed:
 - In the classic notebook interface, I executed a cell which raised an exception; when attempting to scroll to the top of this fairly large cell, my viewport consistently jumps back to the following cell (you can still get to the top of the notebook by dragging the scroll-bar).
 - A "normal" reload (i.e. no cache flush or similar) of the page breaks that behaviour. Now, scrolling over that exception output works normally.
 - Re-executing the failing cell triggers the behaviour again.
 - After a hard-reload (context menu option in Chrome when developer tools are open), some executions of the cell don't seem to trigger the issue; but ultimately, it appeared again.
 
I have made a gist from that particular notebook: https://gist.github.com/burnpanck/490837926c841c00122366137b21dc57
You will find two cells towards the end of the notebook which raise exceptions. Executing those cells a few times, then trying to scroll up does trigger the issue pretty reliably for me. Let me know if that helps.

**Comment by krassowski** [comment]
@burnpanck Would you be able to create a reproducer which does not require installing packages? If the issue is around cell size + timing + exception traceback display, then it should be possible to create a set of cells with just `sleep()` calls, a number of new lines, and a `raise Exception()` calls.

**Comment by burnpanck** [comment]
Unfortunately, the issue seems to appear even with cells that execute rather quickly, so I the timing could be a matter of milliseconds... I have no clue how I would transform that failing example above (or any other for that matter) into a series of sleep calls which still trigger the issue. I will try, but it may take a few days, we're in the middle of a release.

**Comment by jqwhite** [comment]
I observed this issue (erratic scrolling) in Jupyter Lab 4.2.1.  I was able to resolve it by unchecking "Scroll past last cell" in the "Notebook" section of the Preference editor:
<img width="935" alt="Screenshot 2024-06-06 at 12 47 07" src="https://github.com/jupyterlab/jupyterlab/assets/74255929/e017e355-eff9-41dc-90b7-3fac6ee81427">

**Comment by MartinEthier** [comment]
> I observed this issue (erratic scrolling) in Jupyter Lab 4.2.1. I was able to resolve it by unchecking "Scroll past last cell" in the "Notebook" section of the Preference editor: <img alt="Screenshot 2024-06-06 at 12 47 07" width="935" src="https://private-user-images.githubusercontent.com/74255929/337397317-e017e355-eff9-41dc-90b7-3fac6ee81427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NjA3ODcsIm5iZiI6MTcxNzk2MDQ4NywicGF0aCI6Ii83NDI1NTkyOS8zMzczOTczMTctZTAxN2UzNTUtZWZmOS00MWRjLTkwYjctM2ZhYzZlZTgxNDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE5MTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NTZiZjdhYWE4Nzg5MGQ3NTU5MGM4ZWRjYmVlMGVjNWFhYzM1YmExZTgxZTQzOTI4YTE1ZDA4MmYzMTI5OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FKUTJXV_rI8BhYMELhrcV2dOL7MdcO6peJ-49f7DKwg">

I was experiencing this bug with jupyterlab 4.2.1 and this fixed it for me as well.

**Comment by sorenwacker** [comment]
Nope, that did not fix it on my system.

**Comment by pekirt** [comment]
You can find another movie of this same glitch, encountered on Jupyter Lab 4.2.2, here: https://github.com/jupyterlab/jupyterlab/issues/15795#issuecomment-2223182267

**Comment by dilippstauffer** [comment]
I switched from the Safari to the Chrome browser and that fixed it for me.

**Comment by burnpanck** [comment]
I have been using Chrome all along (see initial error description). @dilippstauffer are you sure the effect is fixed for you at all? For me, I can sometimes go for a couple of days without encountering the issue, and then it appears again very persistently.

**Comment by ddemillard** [comment]
What is strange for me is that the notebook will work perfectly fine for awhile until it reaches this state. The simple solution of refreshing the browser resolves the problem immediately. However, it is frustrating when I am submitting jobs and have progress bars and I have to refresh.

II haven't noticed that there is a particular cell or framework/module (pandas) that is causing the issue. The problem appears to be universal across multiple browsers, configurations, and modules but does generally occur when I have a large number of cells.

A fix would be much appreciated as it makes the platform difficult to use.

**Comment by krassowski** [comment]
Just to confirm here, did everyone experiencing the bug experience it using Safari? If yes, which version of Safari? Could you try Safari Technology Preview edition?

**Comment by pekirt** [comment]
I experienced it over more than a year, so several versions of Jupyter and Firefox, on Linux (Mint Mate) and MacOS. I never opted for anything other than latest stable versions of the browsers (and OS's, and other programs).

(I believe Mac doesn't let any other browser operate completely independently so I think there was a bit of Safari in my Firefox. :) ).

**Comment by ddemillard** [comment]
I experience the problem on Chrome both on my Ubuntu desktop as well as using ssh port forwarding (from Ubuntu) on my Windows laptop.

**Comment by sorenwacker** [comment]
My JupypterLab 4.2.0 runs on a Linux system. I connect to it via an ssh tunnel. My notebook runs Chrome in MacOS.

**Comment by ag1988** [comment]
I'm also seeing scrolling jumps. Most of the time it happens when the output of a cell is too long. Clearing the outputs of all cells allows scrolling to the top again.  
jupyterlab 4.2.4 + chrome 127.0.6533.120 + macos sonoma

**Comment by pekirt** [comment]
I first encountered this issue in 3.x .  Now it is 4.2.x and this intermittent issue is encountered in a wide range of versions, browsers, OS's and python packages, if one goes through the various threads on this issue in the past two years. 

One thing I didn't see is... Is it seen on different IDE's? i.e. was it encountered in, say, VSCode with jupyter extension? (I have very recently switched to VSCodium from bare web interface and I haven't encountered the issue yet.)

This is, at least for me, not more than a relatively minor annoyance, but it's an annoyance that has persisted over years and versions. So the issue may possibly have a more fundamental root cause?

**Comment by burnpanck** [comment]
For me, it is a major annoyance. My kind of interactive work often requires repeatedly trying code in a given cell with different parameters. If such a cell is affected, the issue remains pretty repeatable, as described earlier in this thread. Thus, once those scroll glitches start to happen, work becomes extremely inconvenient: I either need to manually drag the scrollbar beyond the affected cell, hoping to be fast enough to get over it without triggering and then find the correct position again, or I have to save the notebook, reload from disk, and also search. At times when I'm doing that kind of work, it has become a major frustration to the point that I had to roll back to jupyter notebook 6 (or whatever it was before the switch to the jupyterlab engine).

I'm working on macOS (currently Sonoma, but previous versions too), usually with Chrome (I may have tested other browsers in the past), and mostly the classic notebook interface, but also with the jupyterlab interface. I don't use in-IDE presentations of jupyter notebooks.

**Comment by johann-petrak** [comment]
This is extremely annoying and impacts the routine work with Jupyterlab notebooks quite a bit.

Experiencing this with Firefox 129.0.1 on Linux and the following Python package versions:
* jupyter: 1.0.0
* jupyterlab: 4.2.4
* jupyterlab_server: 2.27.3
* jupyter_client: 8.6.2
* notebook: 7.2.1

It is hard to check if any Javascipt console messages are directly related to this erratic behavior which randomly occurs. Here is the list of all messages I have after this occurred but some/all of these may be unrelated and may already have been present before:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jlab_core.e5c4c4689689f1651d98.js:1:1403543
Could not resolve location of /home/johann/work-git/project-erdprofi-mb/notebooks/../python/erdprofi_mb/signal.py on server jlab_core.e5c4c4689689f1651d98.js:1:1296116
Path resolution bailing: does not exist jlab_core.e5c4c4689689f1651d98.js:1:1306554
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jlab_core.e5c4c4689689f1651d98.js:1:1403543
Could not resolve location of /home/johann/work-git/project-erdprofi-mb/notebooks/../python/erdprofi_mb/signal.py on server jlab_core.e5c4c4689689f1651d98.js:1:1296116
Path resolution bailing: does not exist jlab_core.e5c4c4689689f1651d98.js:1:1306554
Kernel: restarting (aba87d41-8e05-4a6b-9ffa-3aae5f698316) jlab_core.e5c4c4689689f1651d98.js:1:1373966
Connection lost, reconnecting in 0 seconds. jlab_core.e5c4c4689689f1651d98.js:1:1373349
Starting WebSocket: ws://localhost:8888/api/kernels/aba87d41-8e05-4a6b-9ffa-3aae5f698316 jlab_core.e5c4c4689689f1651d98.js:1:1358830
TypeError: this is undefined
    isReady http://localhost:8888/static/lab/jlab_core.e5c4c4689689f1651d98.js?v=e5c4c4689689f1651d98:1
    x http://localhost:8888/static/lab/jlab_core.e5c4c4689689f1651d98.js?v=e5c4c4689689f1651d98:1
    x http://localhost:8888/static/lab/jlab_core.e5c4c4689689f1651d98.js?v=e5c4c4689689f1651d98:1
    onKernelChanged http://localhost:8888/static/lab/jlab_core.e5c4c4689689f1651d98.js?v=e5c4c4689689f1651d98:1
    m http://localhost:8888/static/lab/jlab_core.e5c4c4689689f1651d98.js?v=e5c4c4689689f1651d98:1
    l http://localhost:8888/static/lab/jlab_core.e5c4c4689689f1651d98.js?v=e5c4c4689689f1651d98:1
    emit http://localhost:8888/static/lab/jlab_core.e5c4c4689689f1651d98.js?v=e5c4c4689689f1651d98:1
    restartKernel http://localhost:8888/static/lab/jlab_core.e5c4c4689689f1651d98.js?v=e5c4c4689689f1651d98:1
jlab_core.e5c4c4689689f1651d98.js:1:1156406
Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early 327.68dbf8491690b3aff1e7.js:1:5783
```

**Comment by wssuzb** [comment]
I experienced the same scrolling bug when using Safari and Chrome, and now I use Microsoft Edge (Version 128.0.2739.67) instead.

**Comment by zard444** [comment]
i have this same issue microsoft edge, unfortunately i cant diagnose why... but its quite frustrating, i thought it related to "find" initially, however even when its clear it still jumps, hope there is a solution soon

**Comment by blajoie** [comment]
JupyterLab Version 4.2.4 + Chrome Version 129.0.6668.71 (Official Build) (64-bit)

Happens to any cell that spans the height of the screen.

**Comment by taylorpool** [comment]
Happens to me too! JupyterLab Version 4.2.5 + Brave Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (64 bit)

**Comment by pekirt** [comment]
> One thing I didn't see is... Is it seen on different IDE's? i.e. was it encountered in, say, VSCode with jupyter extension? 

It's impossible to prove a negative, but I've been using VSCodium (on MacOS and Linux Mint Mate) instead of the bare web interface of jupyter lab for the past ~4 months, and I didn't get this issue during this time. I was getting it with some regularity (but not always) before.

**Comment by ryanlovett** [comment]
Disabling "Scroll past last cell" also worked for me, as reported in https://github.com/jupyterlab/jupyterlab/issues/15968#issuecomment-2153179923. I captured video of the behavior prior to changing the setting, https://www.youtube.com/watch?v=vMTbDNZKrMk.

**Comment by n-splv** [comment]
Same issue - macOS Sonoma 14.7, Brave Browser v1.71.114, JupyterLab 4.2.4.
Disabling "Scroll past last cell" seems to have helped.

**Comment by burnpanck** [comment]
Same here; "Scroll past last cell" did not prevent the issue. The problem is that the issue does not always appear, so sometimes it may appear as if the issue is resolved by some action, but in fact it is not.

**Comment by burnpanck** [comment]
It looks like this issue was reported before as #15795 - at least my experience matches the screen recording reported in that issue.

**Comment by burnpanck** [comment]
Unfortunately, given the somewhat irreproducible behaviour of these potentially related issues, it does seem difficult to even know for sure if the issue does or does not appear in certain configurations.

As the OP of this issue/thread here, all I can say is that for me, the windowing mode did never have any effect (i.e. no matter if `defer`, `none` or `full`), even though it has been suggested to the contrary before: https://github.com/jupyterlab/jupyterlab/issues/15968#issuecomment-2064913085 and the following three comments of this thread. At least for me, my experience that I intended to report in this thread matches the screen-recording of the reporter in https://github.com/jupyterlab/jupyterlab/issues/15795#issuecomment-2223182267, but not the one from #16326, nor the one from [#jupyter/7323](https://github.com/jupyter/notebook/issues/7323). In your latest comment to #15795 you mention that you identified a possible cause that would only be active in `full` mode. I have been experiencing the same behaviour I originally reported in the last few days again quite persistently, and indeed, right now I am in `full` mode. So I will now switch to `none` and report back my observation in the next few days.

**Comment by lwasser** [comment]
I'm following this as i'm running into the same issue. Turning off the scroll past setting doesn't help. I am getting erratic scroll jumping in my browser (chrome on MAC)

**Comment by willingc** [comment]
Hi folks! Echoing @lwasser's comment. She was using JupyterLab in a shared screen while teaching a pyOpenSci workshop. The ability to scroll led to odd screen jumps that seemed like the location on the scroll was being reset while scrolling.

This was unfortunate since it derailed the teaching workflow.

**Comment by willingc** [comment]
@krassowski Once you have some potential fixes in, we would be happy to try them out.

**Comment by psychemedia** [comment]
As with @lwasser , I am seeing this in Chrome on Mac; I also get it in Chrome on a remote windows desktop session.

**Comment by burnpanck** [comment]
... and the jumps have come back on me despite using windowing-mode `none`. So I can confirm again that the issue still persists in both windowing modes `full` and `none`. I had made that same observation earlier also for `defer`, which I did not try again this time. But I guess that rules out the cause identified in [a comment to #15795](https://github.com/jupyterlab/jupyterlab/issues/15795).

**Comment by marcinmarculewicz** [comment]
I have the same issue on Mac's Chrome.

**Comment by SkippyK** [comment]
@burnpanck just wanted to suggest this workaround that I have been using. When I scroll back up I immediately click inside the first code cell I come to. This stops all the jumping and I can continue scolling where I want. It is easier than dragging the scrollbar for me.

**Comment by ducha-aiki** [comment]
Have the same thing right now...

**Comment by krassowski** [comment]
@ducha-aiki using which version? If you are not using the latest version, I suggest trying out 4.3.3 which includes:
- https://github.com/jupyterlab/jupyterlab/pull/16950

That should alleviate some of the scrollbar jitter

**Comment by ducha-aiki** [comment]
@krassowski that is `4.3.3`

```
$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.30.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.5
jupyter_client   : 8.6.3
jupyter_core     : 5.7.2
jupyter_server   : 2.14.2
jupyterlab       : 4.3.3
nbclient         : 0.10.1
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : 7.3.1
qtconsole        : not installed
traitlets        : 5.14.3
```

Moreover, it does very weird scrolling as well - as some cells become invisible, see the screen capture.
On top of that, if I click `b` in command mode, or just simply use icon to create a cell below my current, it creates a cell somewhere else, upper (those empty cells in the video appeared exactly that way)

https://github.com/user-attachments/assets/4c97891c-e0c3-4e92-a0f5-88b55e2517d6

**Comment by krassowski** [comment]
Hmm.. I looks like it is plausible that this issue:
- has the same cause as https://github.com/jupyterlab/jupyterlab/issues/15795
- https://github.com/codemirror/dev/issues/1490

Look out for next alpha release of 4.4.0 as it will include a fix for it.

**Comment by serhiipuzyrov** [comment]
I had the exact problem, in my case change to "defer" in notebook settings helped, also I believe removing those lines helped somehow also to improve the situation:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_rows', 100)

**Comment by mfouesneau** [comment]
@krassowski can you tell me the procedure?

**Comment by krassowski** [comment]
Hmm.. Can you share a notebook in which this is happening? I would be happy to try reproducing.

**Comment by mfouesneau** [comment]
Sadly, no, I cannot share that document. Windowing "None" seems to fix the scrolling issue.

**Comment by burnpanck** [comment]
@mfouesneau did you test thoroughly? As I have mentioned countless times in this thread by now, for me, ultimately, none of the windowing modes made any difference, the issue persisted with them all. However, at least for me, the issue is not fully reproducible, so sometimes everything would seem fine, and all of a sudden it would appear again; I suspect there is a timing issue/race-condition at work here.

**Comment by mfouesneau** [comment]
I did not test fully. the effect was immediate when changing the windowing. I'll test more next week

**Comment by krassowski** [comment]
@burnpanck could you try testing `4.4.0a1`, `4.4.0a2` or `4.4.0a3` release? To reiterate, one bug which was reported as independent of windowing mode was fixed in `4.4.0a1` by upgrading to a patched CodeMirror version.

One potential source of erratic scrolling can be outputs of the cell drastically resizing when being attached. There is an attempt to prevent this in https://github.com/jupyterlab/jupyterlab/pull/17132. If you can notice what kind of widget libraries/outputs you have in the notebooks where the issue happens that might narrow it down.

**Comment by alvin-odins** [comment]
> > This was with jupyterlab==4.2.0a2 and notebook==7.1.1, which, officially, are incompatible
> 
> I am confused, did you see the behaviour in Notebook or in JupyterLab interface?
> 
> > I just found the older bug report [#15795](https://github.com/jupyterlab/jupyterlab/issues/15795), which, from the description, matches the behaviour I see.
> 
> The author of [#15795](https://github.com/jupyterlab/jupyterlab/issues/15795) says that they cannot reproduce this when switching to `full` windowing mode. In JupyterLab 4.2.0b0 it is on by default but you can also change it in Settings Editor → Notebook → Windowing mode. Do you still see this in 4.2.0beta0?
> 
> Also, are you using a trackpad or a mouse?

@krassowski thank you this resolved a similar problem i have been encountering. i set the windowing mode to defer and it resolved the problem.

**Comment by burnpanck** [comment]
@krassowski: I now installed jupyter notebook 7.4.0a3, which, I believe, is based on jupyterlab 4.4.0a3. The widgets in use, where I see the issue most often are either none at all (i.e. the standard jupyter output widget created automatically), or additionally, the tqdm notebook progress bar. The latter doesn't take up a lot of vertical space. The output widget does change its height often, and usually grows pretty large in the cases where the issue appears.

I do have some concerns with the fix attempt in #17132: Given that this issue seems to be hard to reproduce suggests to me that it is some kind of race condition. That fix attempts to solve that by delaying some actions. This sounds like a recipe to cause even more race conditions, possibly mitigating the issue to some degree, but at the same time making it even harder to identify and debug where it persists. I would have preferred if the problem was solved at its root. This must be possible. Before notebook version 7 (when it switched back onto the jupyterlab infrastructure), that issue wasn't there. JavaScript is single-threaded; so there is a strict ordering of events that is observable to the code. Rather than waiting for some delay and hoping for widgets to "settle down", shouldn't we be able to either get notified by the widgets directly, or listen for DOM events to decide when to re-calculate?

**Comment by krassowski** [comment]
> I do have some concerns with the fix attempt in https://github.com/jupyterlab/jupyterlab/pull/17132

I do not like that either, which is why it is marked in draft. I left more in detail explanation of the problems with that PR in https://github.com/jupyterlab/jupyterlab/issues/16326#issuecomment-2566962852

> I would have preferred if the problem was solved at its root. This must be possible. Before notebook version 7 (when it switched back onto the jupyterlab infrastructure), that issue wasn't there

It is not as easy as it sounds. Notebook 6:
- did not have windowing at all, so yes it was not affected by the bug related to windowing
- used older version of CodeMirror which was not affected by the bug in CodeMirror6 that was patched in `4.4.0a3`/`7.4.0a3`

 You can "solve" the issue related windowing by disabling windowing, but then other users complain that this nullifies the performance advantages they got from having it enabled and are no longer able to work with large notebooks that were only made possible with notebook 7.

Imagine a case of three cells, A, B and C. A and C have output with "animation" (rendering really) which resizes from 50px to 150 pixels when they are displayed, while B has output of fixed size 50px. Then imagine viewport has 150px height.

Initially only cell `A` is in viewport:

```
[ A ] 
[ A ]
[ A ]
B
```

Then user scrolls down by 100px and cells `B` and `C` enter the viewport:

```
A
A
[ A ]
[ B ]
[ C ]
```

`C` then resizes to 150px

```
A
A
[ A ]
[ B ]
[ C ]
C
C
```

User scrolls further down by 50px

```
A
A
A
[ B ]
[ C ]
[ C ]
C
```

`A` is now out of viewport and detached. User scrolls up by 100px and cell `A` enters the viewport.

```
A
[ A ]
[ A ]
[ B ]
C
C
C
```

`A` immediately snaps back to 50px of size to trigger the initial "animation", which causes the viewport to cover `C` again.

```
[ A ]
[ B ]
[ C ]
C
C
```

Which triggers `C` to snap back to 50px and trigger the animation. This can lead to either


```
A
A
[ A ]
[ B ]
[ C ]
C
C
```

or

```
[ A ]
[ A ]
[ A ]
B
C
C
C
```

The resizing in the background is what causes the scrollbar to jitter. One could even imagine a case where this leads to viewport bouncing back and forth.

The scenario without windowing is not affected because cells never resize on scroll.

**Comment by krassowski** [comment]
@burnpanck that said, the issue you described initially sounds more akin to the CodeMirror bug and therefore I would like to close this one (as soon as you can confirm the alpha works for you) to avoid splitting discussion between multiple issues and keep the discussion in https://github.com/jupyterlab/jupyterlab/issues/16326

**Comment by burnpanck** [comment]
Could you point me to a description of that CodeMirror bug and/or the fix so that I can try to verify? So far I did not notice any re-appearance of my issue, but I don't consider it having had enough coverage to guarantee its truly fixed. But maybe the bug description allows me to accurately reproduce the issue, thus allowing for a hard proof or rejection of the fix.

**Comment by krassowski** [comment]
@burnpanck:
- https://github.com/jupyterlab/jupyterlab/issues/15795
- https://github.com/codemirror/dev/issues/1490

**Comment by burnpanck** [comment]
Awesome! This might indeed have been the CodeMirror issue. Or at least, with notebook 7.3.2, I was able to reproduce the issue using a large code cell, then scrolling upwards while having some text selected. On the other hand, with notebook 7.4.0a3, I could not reproduce the issue. Closing as resolved in the next release, notebook 7.4.0 / jupyterlab 4.4.0.

**Comment by atifsalam78** [comment]
Run jupyter notebook in safemood 

jupyter notebook --NotebookApp.disable_check_xsrf=True

**Comment by burnpanck** [comment]
@JackLangerman just to verify: Are you sure you are experiencing the exact issue described here? In the past, there has been a lot of confusion about different issues all related to erratic scroll behaviour, but with slightly different symptoms and probably different causes. Here are a number of such issues that have come up in the past (nor sure what the status of them is):
- https://github.com/jupyter/notebook/issues/7323
- #14878
- #15693
- #15795 <- I believe that issue describes the same problem as the issue here
- #16326

**Comment by devanssjc** [comment]
I think I found a possible workaround. The scenario is:

1. Execute a cell with about 100 lines of comments and code that outputs a numeric matrix with approximately 20 lines of data
2. Try and scroll up. Somewhere about halfway up the code cell, the scroll jumps up to the cell above. I can then scroll down ok
3. Try scrolling up from below again, same jumping behavior
4. Manual scroll bar seems to work ok, no jumping

The workaround for this scenario is to click in any cell before scroll to select it. Now I can scroll without jumping behavior

I have not tested this thorough

**Comment by sorenwacker** [comment]
I think it happens when the cell is executing and selected. Unselecting it helps. So, clicking in the cell above for example.

**Comment by krassowski** [comment]
I found something which should help and opened https://github.com/jupyterlab/jupyterlab/pull/17620, can anyone who experiences this regularly (in `full` windowing mode) help to test it by running a code cell with:

```python
from IPython.display import HTML
HTML("<style>.jp-WindowedPanel-viewport { contain: layout }</style>")
```

and reporting if scrollbar is less jittery after the patch?

**Comment by cameronj86** [comment]
> I found my erratic scrolling jumps happen when the search box is active, closing it stops the jumping around

The opposite happened to me. Once I hit `Ctrl+F`, the jumping stopped 🤷🏾‍♂️

**Comment by ronnyli** [comment]
jupyter notebook with safari. The order of the cells starts to jump around as I scroll once my notebook gets large. Running a cell and inserting a new cell below won't show the new cell.

Purely a visual issue since I can inspect the file in VS Code and see the cells are being inserted as expected, and in the expected order.

```
jupyter --version

IPython          : 9.3.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.7
jupyter_client   : 8.6.3
jupyter_core     : 5.8.1
jupyter_server   : 2.16.0
jupyterlab       : 4.4.3
nbclient         : 0.10.2
nbconvert        : 7.16.6
nbformat         : 5.10.4
notebook         : 7.4.3
qtconsole        : not installed
traitlets        : 5.14.3
```

**Comment by krassowski** [comment]
@ronnyli this is unrelated to this issue and tracked in https://github.com/jupyterlab/jupyterlab/issues/16373.

**Comment by Jason-XII** [comment]
I downgraded jupyterlab to 3.6.8 and the scrolling seems normal again.

**Comment by GMC-tech** [comment]
I noticed that the Anaconda Toolbox was kinda interfering with how "reactive" the notebook UI is, so I uninstalled it and that fixed it for me.

For convenience:
1. End all instances of Jupyter Notebook (just to be sure)
2. Close any instance of PowerShell (that runs the Jupyter Notebook)
3. Go to Anaconda Navigator
4. Click Home (left part)
5. Find Anaconda Toolbox
6. Click on the ⚙️ icon.
7. Select **Remove Application**
8. (for assurance) On Anaconda Navigator, go to the upper left, the "File" tab. Hover above it, then click Restart.

try and rehost your Jupyter Notebook and open your project notebook.

```
App versions:
ipykernel        : 6.29.5
jupyter_client   : 8.6.0
jupyter_core     : 5.7.2
jupyter_server   : 2.14.1
**jupyterlab       : 4.4.3**
**notebook         : 7.3.2**
```

Edit [1]:
It was Anaconda Toolbox, not Jupyter.

**Comment by johann-petrak** [comment]
> I noticed that the Jupyter Toolbox was kinda interfering with how "reactive" the notebook UI is, so I uninstalled it and that fixed it for me.

@GMC-tech   What is the exact name of that package? I do not see any package related to jupyter with "tools" in the name installed and I do see those erratic jumps.

**Comment by kuhlaid** [comment]
I created what seems to be reproduceable test case for 'scroll jumping'. The use-case instructions are the first few lines of the Notebook. A link to the Notebook and a video screencast of the behavior can be found at [https://gist.github.com/kuhlaid/830da06d9bed84132386b34bc68b74e1](https://gist.github.com/kuhlaid/830da06d9bed84132386b34bc68b74e1).

I notice the scroll behavior of this Notebook in both https://jupyter.org/try-jupyter/lab/ and my local version of JupyterLab running Version 4.4.3, using the latest Firefox browser (v140.0) on Windows.

**Comment by spacediver99** [comment]
I have also experienced similar issues (scrolling issues, disappearing cells). Often the only way to restore the missing cells is to reload the notebook. 

Using jupyter notebook Version: 7.4.3 with jupyterlab 4.4.3 (though I only use stand alone notebooks), and latest version of Chrome.

**Comment by krassowski** [comment]
I wonder if https://github.com/jupyterlab/jupyterlab/pull/17620 will solve it for you. It has not been released yet though, so not easy to test.

**Comment by spacediver99** [comment]
Thanks @krassowski, I'll wait until it's released. If the issue still persists after that I'll report back here.

**Comment by Jason-XII** [comment]
I downgraded jupyter lab to 3.x versions and the problem no longer exists.

**Comment by krlawrence** [comment]
I'm seeing the same scroll jumping (and related issues) with scrolling and/or jumping to the wrong place using the markdown TOC in the sidebar. At times it makes the notebook borderline unusable it gets so bad. Still seeing it in JupyterLab 4.4.3

**Comment by Carl-McBride-Ellis** [comment]
As mentioned earlier, switching the notebook pane to be full width (Linux: toggle using `CTRL-b`) and back again seems to be a quick fix.
(JupyterLab version: 4.4.2 with Firefox)

**Comment by krassowski** [comment]
JupyterLab 4.4.4 is out and hopefully it should somewhat help.

**Comment by jpwgnr** [comment]
I still have the jumps in 4.4.4 unfortunately.

**Comment by gscout** [comment]
> I still have the jumps in 4.4.4 unfortunately.

I can confirm this as well

**Comment by spacediver99** [comment]
Same, although I notice now that if i scroll back and forth a few times "across the jump", it sometimes resolves. Not sure if it used to do that.

Also, another behaviour that I don't think existed before. If you scroll the notebook so that a particular cell is only partially visible and is at the top of the screen, and then run that cell, the notebook automatically scrolls so that the cell is fully visible.

**Comment by ajfriend** [comment]
> I still have the jumps in 4.4.4 unfortunately.

Same here.

**Comment by pupeno** [comment]
Same on both Notebook and Lab, 4.4.4, in Windows, in Vivaldi.

**Comment by darien-schettler** [comment]
Same

**Comment by aimgo** [comment]
Same on Ubuntu+ Chrome, 7.4.0

**Comment by krassowski** [comment]
I believe this should be largely fixed with JupyterLab `4.4.5` (just released). Apologies for getting the fix wrong in 4.4.4. @kuhlaid can you upgrade JupyterLab to 4.4.5 and test with your reproducer in full windowing mode? I did not see the issue anymore in 4.4.5.

**Comment by hey2022** [comment]
Unfortunately I still have the issue on 4.4.5.

**Comment by GregHilston** [comment]
Unfortunately I still have the issue on 4.4.5. as well

> Firefox 140.0.4 (aarch64)
> MacOS 15.5 (24F74)

**Comment by kuhlaid** [comment]
Hi @krassowski , I updated my local JupyterLab to 4.4.5 (`pip install jupyterlab==4.4.5`) and ran the test Notebook again (https://gist.github.com/kuhlaid/830da06d9bed84132386b34bc68b74e1). I did not experience any scroll skipping, so at least with this test it looks like 4.4.5 corrected the issue. Thank you so much.

https://jupyter.org/try-jupyter/lab/ still has the scrolling issue but I am assuming it is still running an earlier version of JupyterLab (I cannot determine the version it is using).

**Comment by spacediver99** [comment]
I'm still getting scrolling jumps/disappearing cells.

windows 10, chrome Version 138.0.7204.158 (Official Build) (64-bit)

IPython          : 9.2.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.7
jupyter_client   : 8.6.3
jupyter_core     : 5.7.2
jupyter_server   : 2.16.0
jupyterlab       : 4.4.5
nbclient         : 0.10.2
nbconvert        : 7.16.6
nbformat         : 5.10.4
notebook         : 7.4.3
qtconsole        : not installed
traitlets        : 5.14.3

**Comment by lboogaard** [comment]
fwiw, this is still present using the latest version in firefox on macos

**Comment by Jason-XII** [comment]
Quick fix:
`pip install jupyterlab==3.6.7`

**Comment by pre-mRNA** [comment]
Also having the issue, latest chrome on MacOS

**Comment by zoravur** [comment]
Another thing I've found that works is spamming Shift+Enter to force the intermediate cells to load, and afterwards I can scroll smoothly (although this also runs the cells)

**Comment by spacediver99** [comment]
Not sure if this is at all related, but I've also noticed that with newer versions (not sure if it's of notebook  or jupyterlab) that if you have a cell that is large enough that it can be scrolled down far enough such that the top of the cell is not visible, and you then run that cell, the notebook automatically jumps so that the top of the cell is visible.

Not sure if this is intentional behaviour (personally I prefer if it wouldn't automatically jump), but if it's not intentional, may be related.

**Comment by MoRanjbarDi** [comment]
- I use vs-code Jupyter extension and this glitch _only_ occurs when I switch windows (browser<->vs-code) with **alt+tab** rather than clicking them on dock.

- **I could fix it** by installing `imwheel` as discussed [here](https://askubuntu.com/questions/1075621/how-to-solve-a-scrolling-misbehavior-after-doing-alttab)

p. s. : installing imwheel will kill your ctrl+wheel zoom initially; but you can fix it with a simple config discussed [here](https://github.com/freeplane/freeplane/issues/134#issuecomment-1242629624) --remember to fine-tune the app list in first line.

**Comment by krassowski** [comment]
> I use vs-code Jupyter extension and this glitch only occurs when I switch windows

In that case you are likely experiencing a very different bug as code shared between vscode-jupyter and jupyterlab is minimal and the UI implementations are completely different. I saw other reports for scrolling issues in VSCode, e.g.  https://github.com/microsoft/vscode-jupyter/issues/15747 - this one might be different but in any case please report it in that repo.

**Comment by SombiriX** [comment]
This is more of a workaround than a fix but changing the windowing mode in Notebook settings to "none" fixed the erratic jumping for me. 

<img width="1643" height="289" alt="Image" src="https://github.com/user-attachments/assets/adb58468-b7b0-49c7-afa2-fd52f542cb62" />

eta: I'm running 4.4.3

**Comment by EkebergByte** [comment]
> This is more of a workaround than a fix but changing the windowing mode in Notebook settings to "none" fixed the erratic jumping for me.
> 
> <img alt="Image" width="1643" height="289" src="https://private-user-images.githubusercontent.com/20493358/475246442-adb58468-b7b0-49c7-afa2-fd52f542cb62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ2NTg0MjYsIm5iZiI6MTc1NDY1ODEyNiwicGF0aCI6Ii8yMDQ5MzM1OC80NzUyNDY0NDItYWRiNTg0NjgtYjdiMC00OWM3LWFmYTItZmQ1MmY1NDJjYjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODA4VDEzMDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzBiZTJlM2Q0ZjgyNzA2ZjYyN2YzMzgzYjY1M2QxN2M3ZTQwNTJlYTZkNjkzYWM3OWFjZDJmZjU5OTE5ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IjSCoYPZqv0hQazYvKXxuiz8a8deNQ3yTjzjXELrd0c">
> eta: I'm running 4.4.3

Thank you for sharing this workaround!
 I had a persistent issue in Jupyter Notebook where scrolling down through a file with the mouse wheel was impossible — the view kept jumping back to the top automatically, making it unusable.

 Changing the **windowing mode** in Notebook settings to `"none"` resolved the problem completely.

 **Environment details:**

 ```
 IPython          : 8.30.0  
 ipykernel        : 6.29.5  
 ipywidgets       : 8.1.5  
 jupyter_client   : 8.6.3  
 jupyter_core     : 5.7.2  
 jupyter_server   : 2.15.0  
 jupyterlab       : 4.3.4  
 nbclient         : 0.10.2  
 nbconvert        : 7.16.6  
 nbformat         : 5.10.4  
 notebook         : 7.3.2  
 qtconsole        : 5.6.1  
 traitlets        : 5.14.3  
 ```

 OS: \[Windows 11
 Browser: \[Opera] - Chromium version:135.0.7049.115


 Hopefully this helps others facing the same problem.

**Comment by krassowski** [comment]
Thank you all for commenting here. If anyone can provide a reproducer I am happy to work on fixing more cases.

**Comment by samkovalypison** [comment]
> This is more of a workaround than a fix but changing the windowing mode in Notebook settings to "none" fixed the erratic jumping for me.
> 
> <img alt="Image" width="1643" height="289" src="https://private-user-images.githubusercontent.com/20493358/475246442-adb58468-b7b0-49c7-afa2-fd52f542cb62.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUwMjAwNzcsIm5iZiI6MTc1NTAxOTc3NywicGF0aCI6Ii8yMDQ5MzM1OC80NzUyNDY0NDItYWRiNTg0NjgtYjdiMC00OWM3LWFmYTItZmQ1MmY1NDJjYjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODEyVDE3MjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMTBjYTU4NjdjNzljN2JiM2ExZTFiYjhlMTcxZjgxZTllZWFmNzBmOTU2MzIwMmUwNTAwZTkzZjcwYTgyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t6kgN_xihS5NjIYU3OwSWbLcinwrFt-7B5eaCnS9HzM">
> eta: I'm running 4.4.3

Thank you!!

**Comment by bzamecnik** [comment]
It seems to be related (possibly duplicate) to https://github.com/jupyterlab/jupyterlab/issues/16326.

**Comment by krassowski** [comment]
> possibly duplicate

It's not a duplicate because the edge case discussed in that issue was fixed by #17339. What would be immensely useful is more information how to reproduce the remaining edge cases so that someone can work on fixing them.

**Comment by spacediver99** [comment]
Here's one that causes issues. 

Hard to reproduce reliably, and unclear what aspects of this are necessary/sufficient

Try running all cells one at a time in order, then repeat from top to bottom and try scrolling. If issue doesn't manifest, try running cells in random order while testing scrolling. 

I'll try to come up with a more reproducible example, but this is the best I have for now:

https://github.com/spacediver99/scroll-issue-notebook/blob/main/erratic_scroll.ipynb

**Comment by fkerem** [comment]
> This is more of a workaround than a fix but changing the windowing mode in Notebook settings to "none" fixed the erratic jumping for me.
> 
> <img alt="Image" width="1643" height="289" src="https://private-user-images.githubusercontent.com/20493358/475246442-adb58468-b7b0-49c7-afa2-fd52f542cb62.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUzNzM5ODksIm5iZiI6MTc1NTM3MzY4OSwicGF0aCI6Ii8yMDQ5MzM1OC80NzUyNDY0NDItYWRiNTg0NjgtYjdiMC00OWM3LWFmYTItZmQ1MmY1NDJjYjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODE2VDE5NDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NmQ2OTFmMjgxMTZlZDI1Y2I2OTY5ZTg1YjE5N2I2YjRjZDk5Zjg2Y2YyZjgzMjliMzJkNDRmNWZmYTIzNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.trOSV-lYzUsJtPrK6N4V1gYImQoXTGqXC6Ce85m0mYE">
> eta: I'm running 4.4.3

This solved my issue as well, thank you so much for sharing!!

**Comment by spacediver99** [comment]
Is that windowing mode fix available in notebook? I don't use lab.

**Comment by samkovalypison** [comment]
> Here's one that causes issues.
> 
> Hard to reproduce reliably, and unclear what aspects of this are necessary/sufficient
> 
> Try running all cells one at a time in order, then repeat from top to bottom and try scrolling. If issue doesn't manifest, try running cells in random order while testing scrolling.
> 
> I'll try to come up with a more reproducible example, but this is the best I have for now:
> 
> https://github.com/spacediver99/scroll-issue-notebook/blob/main/erratic_scroll.ipynb

It happens to me about 90% of the time. I believe it has to do with having a lot of tabs open on the notebook instance, and each tab containing a notebook that is very long with many outputs. Changing the windowing mode to none completely solved it for now.

**Comment by hvntxd** [comment]
**from https://discourse.jupyter.org/t/scrolling-bug-makes-my-screen-shake-erratically/32421/2:** 
_“Settings → Settings Editor → Notebook → Windowing mode → none”_

This helped me

**Comment by shaneob2718** [comment]
> This is more of a workaround than a fix but changing the windowing mode in Notebook settings to "none" fixed the erratic jumping for me.
> <img alt="Image" width="1643" height="289" src="https://private-user-images.githubusercontent.com/20493358/475246442-adb58468-b7b0-49c7-afa2-fd52f542cb62.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTcwMTE5MTgsIm5iZiI6MTc1NzAxMTYxOCwicGF0aCI6Ii8yMDQ5MzM1OC80NzUyNDY0NDItYWRiNTg0NjgtYjdiMC00OWM3LWFmYTItZmQ1MmY1NDJjYjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA0VDE4NDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MjRkMDQ5YjE5N2VkNDA0ZmQ1YWRiMzA1YWZkZWRiZTFlZGZjMzQxNjYzYzY1Nzc4ZGU4MGQ4NmU3ZmE2MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZvPK6IDvlAL0CVaRFgW-UOCvvTT3aVxnOMAaoNTtbDk">
> 
> eta: I'm running 4.4.3

I was having this same issue on a rather lage notebook I was working in and this seems to have fixed it, thank you!

**Comment by fperez** [comment]
Hi all - this is an old issue but it continues to be frustratingly stubborn and, in some cases, a real drag on usability. 

I have finally been able to find [a public notebook that reliably triggers the problem, my "Git Visuals" lecture here](https://github.com/UCB-stat-159-f25/site/blob/main/lectures/intro-git/git-visuals.ipynb).

I've tested on JLab 4.4.7, and this shows clearly the distracting jumps. It drove me crazy during teaching this week :)

https://github.com/user-attachments/assets/470f314f-e272-4866-a54a-b5e51f0517be

Unfortunately, in this case setting `Windowing Mode` to `none` as suggested does fix the jumping, but it then makes the first cell render with a giant block of whitespace that isn't supposed to be there:

https://github.com/user-attachments/assets/878aa86b-6b1c-40b6-950a-4efc23174139

@krassowski - I know you've looked at this a lot, many thanks for that! I hope having an easily reproducible case like this could help track down the problem. 

I am happy to test further if helpful, I wish I had enough web expertise to help fix it :)

**Comment by jtpio** [comment]
> Unfortunately, in this case setting `Windowing Mode` to `none` as suggested does fix the jumping, but it then makes the first cell render with a giant block of whitespace that isn't supposed to be there:

This seems to happen when going back to the already opened notebook after the changing the windowing setting.

Can you try closing the notebook and then reopening it? It seems to be helping avoid having this blank space.

> I am happy to test further if helpful, I wish I had enough web expertise to help fix it :)

@fperez thanks for providing an example notebook and the screencasts!

There is ongoing work to look into leveraging the browser `content-visiblity` as an alternative to the `full` mode in:
- https://github.com/jupyterlab/jupyterlab/issues/16327
- https://github.com/jupyterlab/jupyterlab/pull/17822

Would you be able to try to the PR on Binder to see if it already helps fix these scrolling issues?

- https://mybinder.org/v2/gh/Meriem-BenIsmail/jupyterlab/content-visibility?urlpath=lab
- Use `File > Open from URL...` to open your notebook: https://raw.githubusercontent.com/UCB-stat-159-f25/site/refs/heads/main/lectures/intro-git/git-visuals.ipynb

**Comment by jtpio** [comment]
FYI a new 4.5 alpha release is now available, with a new `contentVisibility` mode for the notebook: https://github.com/jupyterlab/jupyterlab/releases/tag/v4.5.0a4

To enable this mode: `Settings → Settings Editor → Notebook → Windowing mode → contentVisiblity`

https://github.com/user-attachments/assets/3925fe92-764f-4a45-96e7-e0ae22d03e13

It would be great if folks could try this release with this new mode, to see if it already helps fix some scrolling issues. Thanks!

**Comment by SebastianStrasserVexcel** [comment]
4.5.0a4 with contentVisibility mode seems to fix the erratic scroll jumps and cells not being rendered while scrolling for me. I've tried two notebooks where I can reliably reproduce these issues in 4.4.4 and had no issues with 4.5.0a4. Great work!

**Comment by fperez** [comment]
Yup, can confirm that 4.5.0a4 with contentVisibility mode also seems to work for me!

I'm still getting that weird "stray white block" at the start, but a simple reload made it go away, so mentioning it only for reference.

Thanks all! I hope this problem can be put to rest once and for all, it's been a long-standing major annoyance.

Should `Windowing mode → contentVisiblity` be the default henceforth? It's a bit of an obscure setting, and users who run into the problem can easily just live with it (and be annoyed like I was) instead of knowing to go digging into the settings for that fix...

Or does it have other significant downsides? In any case, thanks again for the response @jtpio & team!

**Comment by jtpio** [comment]
Nice, thanks for testing the pre-release!

> Should `Windowing mode → contentVisiblity` be the default henceforth? It's a bit of an obscure setting, and users who run into the problem can easily just live with it (and be annoyed like I was) instead of knowing to go digging into the settings for that fix...

Compared to the `full` mode, this new mode is still lacking support for the minimap. But this will likely be fixed soon by https://github.com/jupyterlab/jupyterlab/pull/17904.

The idea would then be to make this new mode the default for the 4.5 beta cycle, so users get to try it without having to change the settings. If there is no major issue, it can stay the default for the 4.5 final release.

It would be great to have as much feedback as possible, so for folks in this thread who have been experiencing scrolling issues, please try the `4.5.0a4` release and comment here if it fixes your issue. Thanks!

**Comment by yberreby** [comment]
This bug has been ruining my Jupyter experience for a long time now. I tried the `4.5.0a` release with `contentVisibility` and things now seem fine!

**Comment by csala** [comment]
@jtpio Does this setting change in jupyterlab affect the standalone notebook run with `jupyter notebook`?

**Comment by jtpio** [comment]
> Does this setting change in jupyterlab affect the standalone notebook run with `jupyter notebook`?

This setting it also now available in Jupyter Notebook `7.5.0a3`:

https://github.com/user-attachments/assets/0d33c8cb-f160-4c75-a07f-ee950b4d5304

**Comment by csala** [comment]
Thanks for the quick reply @jtpio!
So far, I had already tried installing jupyterlab only to change the setting there, and I can confirm that after that the erratic scrolling went away also when running plain `jupyter notebook`. I have not tried with the standalone `7.5.0a3`

**Comment by mazurkin** [comment]
Did anyone find the way to set "Windowing mode" in the command line of the Jupyter server?

**Comment by krassowski** [comment]
Not via CLI but you can do that with [`overrides.json` file](https://jupyterlab.readthedocs.io/en/latest/user/directories.html#overrides-json). The beta of 4.5.0 to be released soon will have the `content-visibility` as default.

**Comment by jtpio** [comment]
> I'm still getting that weird "stray white block" at the start, but a simple reload made it go away, so mentioning it only for reference.

@fperez would you be able to try the `4.5.0b0` release, which has the `contentVisiblity` mode enabled by default?

We are trying to reproduce this "stray white block" issue, and were wondering if it was only happening when switching from the `full` mode to another mode in a running JupyterLab instance (since refreshing the page "fixes" the issue).

**Comment by Erzsebeteemk** [comment]
In the Jupiter Notebook also this is works for me: Settings → Settings Editor → Notebook → Windowing mode → Defer. / I have not yet Content visibility./

**Comment by Nick-Kinsella** [comment]
@Erzsebeteemk This worked great. Thank you

**Comment by Erzsebeteemk** [comment]
> [@Erzsebeteemk](https://github.com/Erzsebeteemk) This worked great. Thank you

My pleasure.

**Comment by brandonrobertz** [comment]
> In the Jupiter Notebook also this is works for me: Settings → Settings Editor → Notebook → Windowing mode → Defer. / I have not yet Content visibility./

This fixed it for me too. TYSM!

**Comment by Erzsebeteemk** [comment]
> > In the Jupiter Notebook also this is works /for me: Settings → Settings Editor → Notebook → Windowing mode → Defer. / I have not yet Content visibility./
> 
> This fixed it for me too. TYSM!

I’m glad to hear that!

**Comment by afeld** [comment]
Tested things out:

Jupyter version | Windowing mode | Experience
--- | --- | ---
4.4.10 | `full` | jumpy 👎 
4.4.10 | `defer` | smooth 👍 
4.5.0b1 | `full` | jumpy 👎 
4.5.0b1 | `defer` | smooth 👍 
4.5.0b1 | `contentVisibility` | smooth 👍 

Thanks!

**Comment by jtpio** [comment]
JupyterLab 4.5.0 is now available: https://github.com/jupyterlab/jupyterlab/releases/tag/v4.5.0

Jupyter Notebook 7.5.0 is also available: https://github.com/jupyter/notebook/releases/tag/v7.5.0

And they both ship with the `contentVisibility` mode enabled by default.

Would people here be able to try the latest release, and confirm this fixes most of the scrolling issues? Thanks!

**Comment by celestinoxp** [comment]
I still have issues :(
I'm still having problems with JupyterLab; sometimes the scrolling jumps to the end or beginning of the page, and sometimes it's blank. So if I reduce the window width, the cells appear...

**Comment by krassowski** [comment]
@celestinoxp can you share more information? is this with `contentVisibility` mode in 4.5.0? What browser do you use?

**Comment by celestinoxp** [comment]
> [@celestinoxp](https://github.com/celestinoxp) can you share more information? is this with `contentVisibility` mode in 4.5.0? What browser do you use?


Windows 11
Google Chrome

! jupyter --version
Selected Jupyter core packages...
IPython          : 9.7.0
ipykernel        : 7.1.0
ipywidgets       : 8.1.8
jupyter_client   : 8.6.3
jupyter_core     : 5.9.1
jupyter_server   : 2.17.0
jupyterlab       : 4.5.0
nbclient         : 0.10.2
nbconvert        : 7.16.6
nbformat         : 5.10.4
notebook         : not installed
qtconsole        : 5.7.0
traitlets        : 5.14.3

Windowing mode: full

**Comment by krassowski** [comment]
> Windowing mode: full

This is in some way expected; you need to switch to `contentVisibility` to benefit from these changes, which is the default in 4.5.0. It might be that when changing settings in an older version the full mode was saved as your preference.

**Comment by PhilippVerpoort** [comment]
Upgrading to 4.5.0 worked for me.

**Comment by ortollj** [comment]
Once the code reaches a certain size, the Jupyter text editor starts jumping unexpectedly when scrolling. It's really annoying.

Selected Jupyter core packages...
IPython          : 8.18.1
ipykernel        : 6.27.1
ipywidgets       : 8.1.1
jupyter_client   : 8.3.1
jupyter_core     : 5.3.2
jupyter_server   : 2.7.3
jupyterlab       : 4.1.3
nbclient         : 0.8.0
nbconvert        : 7.9.2
nbformat         : 5.9.2
notebook         : 7.1.1
qtconsole        : not installed
traitlets        : 5.14.3

**Comment by krassowski** [comment]
> Once the code reaches a certain size, the Jupyter text editor starts jumping unexpectedly when scrolling. It's really annoying.

> jupyterlab : 4.1.3

This and other bugs around scrolling were fixed a long time ago. You need to upgrade to the latest JupyterLab version (4.5.2 as of today) if you want to benefit from bug fixes.

**Comment by edward-b-1** [comment]
I still have this problem with version `4.5.5`. I just transferred a git repo containing many `ipynb` files to a different machine. I didn't see these issues on the machine I was using previously.

If you want to fix this issue and can tolerate slower notebook opening times (I haven't found this to be a particular problem, even though I have some pretty large notebooks) then try changing the **Windowing Mode** setting to **none**.

<img width="1221" height="581" alt="Image" src="https://github.com/user-attachments/assets/2e185463-2176-4bb4-aec8-7586c39a36ab" />

**Comment by savchenko** [comment]
> If you want to fix this issue and can tolerate slower notebook opening times (I haven't found this to be a particular problem, even though I have some pretty large notebooks) then try changing the Windowing Mode setting to none.

I can confirm that screen jump _reliably_ happens every time I press <kbd>Ctrl+Enter</kbd> with `Windowing Mode` set to `none`.

Jupyter Lab version 4.5.7

**Comment by krassowski** [comment]
@savchenko and I see that you found the issue where this is tracked (https://github.com/jupyterlab/jupyterlab/issues/16505).

**Comment by finnmishler05** [comment]
Issue persists currently.
