### ISSUE TITLE
Cannot open notebooks with stream in outputs in JupyterLab 4.3.0b0-1

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#16812]
## Description

A critical performance regression in JupyterLab 4.3.0b0 was identified in testing: notebooks with large amount of stream data in outputs no longer open in reasonable time.

While users are reporting that notebooks do not open at all, it appears that the time opening a notebook is now a quadratic or exponential function of stream data content, which may indicate that some previously functional notebooks will not open before the heat death of the universe.

This was most likely:
- introduced in https://github.com/jupyterlab/jupyterlab/pull/16498, and
- not fixed by https://github.com/jupyterlab/jupyterlab/pull/16692

CC @davidbrochart

## Reproduce

1. Download the attached notebook [50_char_500_lines.json](https://github.com/user-attachments/files/17131015/50_char_500_lines.json) file
2. Rename it to `50_char_500_lines.ipynb` - it has only one code cell and only one output
3. Open it in JupyterLab 4.3
4. See that it takes 10-15 seconds to open (depending on the browser)

The single output of the cell looks like this:

```js
{
     "name": "stdout",
     "output_type": "stream",
     "text": [
         "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
         /* of different lengths, repated many times */
         "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"
     ]
}
```

Timings in Chrome:
- 50 characters repeated in 100 lines took 0.3s to load
- 50 characters repeated in 200 lines took 1.4s to load
- 50 characters repeated in 500 lines took 8s to load
- 50 characters repeated in 1000 lines took 30s to load

Timings in Firefox:
- 50 characters repeated in 500 lines took 15s to load
- 50 characters repeated in 1000 lines took 93s to load

I have not tested Safari but I would expect even worse timings.

## Expected behavior

Notebooks opens as fast as in JupyterLab 4.2 (or faster) where even the test notebook with 1000 lines takes **less than one second** to open.

## Context

- Browser: Chrome and Firefox
- JupyterLab version: 4.3.0b0 and 4.3.0b1

Here is the relevant flame graph:

![image](https://github.com/user-attachments/assets/306cf581-16f6-4aa7-b680-9a75ad34cd06)

**Comment by krassowski** [comment]
From JupyterLab point of view the bug is in https://github.com/jupyter-server/jupyter_ydoc, in `YNotebook.fromJSON()` function. Over 90% of the stack graph displayed above is on the `jupyter_ydoc` side.

**Comment by davidbrochart** [comment]
Thanks for the ping @krassowski.
I think this is due to the [inefficient stream processing](https://github.com/jupyterlab/jupyterlab/pull/16498#issuecomment-2218002348) that was introduced in #16498. Previously we were using regex, so it was fast, but unfortunately [buggy](https://github.com/jupyterlab/jupyterlab/issues/16515).
I'll take a look at optimizing the processing, at least taking shortcuts for simple cases such as the one reported here.

**Comment by davidbrochart** [comment]
I opened #16814, but it's really https://github.com/jupyter-server/jupyter_ydoc/pull/275 which should fix this issue.

**Comment by davidbrochart** [comment]
jupyter-ydoc v3.0.0.a8 should fix this issue.

**Comment by davidbrochart** [comment]
Hmm actually I cannot confirm that it fixed the issue, still investigating.

**Comment by davidbrochart** [comment]
Ah yes, I can confirm it is fixed, sorry for the confusion.

**Comment by krassowski** [comment]
For a outputs without `\r` or `\b` the PR https://github.com/jupyterlab/jupyterlab/pull/16814 did fix it. But for large outputs with `\r` or `\b` I still see the issue in the test case added in https://github.com/jupyterlab/jupyterlab/pull/16815 with `jupyter-ydoc-3.0.0a8`. https://github.com/jupyterlab/jupyterlab/pull/16815 should ultimately close this though - I will post the benchmarks in there.

**Comment by davidbrochart** [comment]
We require `^3.0.0-a5` so that should allow v3.0.0a8 to be installed, right?

**Comment by davidbrochart** [comment]
> for large outputs with `\r` or `\b` I still see the issue in the test case added in #16815 with `jupyter-ydoc-3.0.0a8`

Note that it is expected to have worse performances compared to when we were using a regex. The latter was fast but buggy for those cases.

**Comment by krassowski** [comment]
> We require ^3.0.0-a5 so that should allow v3.0.0a8 to be installed, right?

Kind of. The Python package? Unrelated, the pin is in `pyproject.toml`. JS assets included in release? These are taken from resolutions in `yarn.lock`. So while we do not have to update the pin to `^3.0.0-a8` (though I did it locally for testing) weat least need to update the yarn lock file to ensure this is used in the released code.

**Comment by davidbrochart** [comment]
> we at least need to update the yarn lock file

Indeed.
