### ISSUE TITLE
RTC: prefix appears when saving newly created file on first save

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlab/jupyterlab#16914]
## Description

When [Jupyter Collaboration](https://github.com/jupyterlab/jupyter-collaboration) is installed and enabled, when saving a newly created file for the first time, the "first save" dialog appears with the `RTC:` prefix on the filename. For example, if the displayed filename is `Untitled21.ipynb`, the suggested name in the first save dialog is `RTC:Untitled21.ipynb`:

![image](https://github.com/user-attachments/assets/de41dfb8-25a2-4503-bef3-96614979183f)

## Context

- OS and version: macOS "Sonoma" 14.7 (23H124)
- Browser and version: Firefox 131.0.2 (aarch64)
- JupyterLab version: 4.3.0

**Comment by JasonWeill** [comment]
See also:

* https://github.com/jupyterlab/jupyterlab/pull/16744
* https://github.com/jupyterlab/jupyterlab/pull/16794

**Comment by jtpio** [comment]
Thanks @JasonWeill for opening the issue.

The other ways for renaming a notebook don't seem to be including the `RTC:` prefix in the dialog input. So maybe this is specific to the first save dialog logic which should be fixed?

**Comment by krassowski** [comment]
For some dialogs keeping the drive prefix sounds useful, for example if we had "Move file" dialog it would allow users to move a file between drives. Similarly, it would be useful to allow "Save as" to include prefix. For rename dialog the predominant use case would be renaming the file without moving it between drives so the prefix does not make sense here indeed.

**Comment by JasonWeill** [comment]
@jtpio Yes, the other "rename file" dialog that you can access by right-clicking on the document tab inside JupyterLab does not show the `RTC:` prefix. This does seem to be restricted to the first save dialog.

**Comment by krassowski** [comment]
While RTC will no longer use a custom drive with `RTC:` prefix in future releases, this issue is still relevant to files on custom drives - I re-titled it to reflect this.
