### ISSUE TITLE
Pressing enter in text editor types 'from' when autocompletion enabled

### ISSUE THREAD

**Issue by makamsumukh541** [jupyterlab/jupyterlab#16931]
## Description

When the autocompletion is enabled from the settings, on pressing enter to go new line, 'from' is added at the beginning of the new line automatically.
## Reproduce

1. Go to 'Settings' then to 'Code Completion'
2. Select 'Enable autocompletion' 
![Screenshot 2024-11-06 at 2 48 56 PM](https://github.com/user-attachments/assets/e0a79d75-d98c-4720-9616-52451d336b5c)
3. Open one of your file.py 
4. Go to end of one of the lines 
![Screenshot 2024-11-06 at 2 48 25 PM](https://github.com/user-attachments/assets/6383ebca-ffc5-489d-9cab-f0a345e58b45) 
5. Press enter
![Screenshot 2024-11-06 at 2 48 37 PM](https://github.com/user-attachments/assets/04bbdb57-1ee2-4827-974d-88fc4bdcd74d)
6. 'from' appears at the beginning of the line

## Expected behavior
'from' should not appear on pressing enter to enter new line.

## Context

- Operating System and version: MacOS Monterey 12.7.6
- Browser and version: Brave 1.70.126 
- JupyterLab version: 4.1.0

**Comment by krassowski** [comment]
Could it be that the completer is shown but it is not visible beause it is outside of the viewport and by pressing enter you are accepting the suggestions generated from tokens available in the file? Could you add a few empy lines at the end of the file and try reproducing again?

> JupyterLab version: 4.1.0

That's a very old version, it could be that there was an error like describe above which was fixed since.

**Comment by makamsumukh541** [comment]
I face the same issue when I press enter to add a new line in between the codes.


![Screenshot 2024-11-06 at 4 02 33 PM](https://github.com/user-attachments/assets/39bfd0cd-4a26-48d2-a767-55303ecc0440)
- On pressing enter

![Screenshot 2024-11-06 at 4 03 06 PM](https://github.com/user-attachments/assets/d6865ffa-80ec-456c-8646-7d3ff403b4d8)

**Comment by makamsumukh541** [comment]
> Could it be that the completer is shown but it is not visible beause it is outside of the viewport and by pressing enter you are accepting the suggestions generated from tokens available in the file? Could you add a few empy lines at the end of the file and try reproducing again?

Sorry, I get what you are saying now. Yes, when I added empty lines at the end of the page and then try to add new line by pressing enter in those empty lines I do not get 'from' anymore. However, I still get it when I try to add new line anywhere else. Is there any solution to this?

> 
> > JupyterLab version: 4.1.0
> 
> That's a very old version, it could be that there was an error like describe above which was fixed since.

**Comment by JasonWeill** [comment]
@makamsumukh541 As @krassowski mentioned, JupyterLab 4.1.0 is now two minor versions out of date; we recently released version 4.3.0, and the 4.2.x series has been generally available for over 6 months. Can you please try to reproduce this behavior with a newer version and let us know what you see? Thanks!

**Comment by JasonWeill** [comment]
@krassowski Is this fixed as a result of #16847 / #16863?

**Comment by krassowski** [comment]
I would think this is unrelated

**Comment by 3coins** [comment]
@makamsumukh541 
Checking back on this issue, if you were able to try the latest release v4.3.1 for this issue and can share the results?

**Comment by andrii-i** [comment]
In JupyterLab 4.3.1 when Enter is pressed while caret is at the end of the line, caret moves to the new line and auto-completion window appears. So this behavior appears to be solved in the latest version of JupyterLab. Auto completion window behavior is tracked in https://github.com/jupyterlab/jupyterlab/issues/15013
