### ISSUE TITLE
Cells sometimes do not render when scrolling down in presence of large outputs

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab#17023]
> Sorry about the long video, I uploaded to drive to share
> https://drive.google.com/file/d/1M-SWdCYkUSu0xcF1qmb6ZyvDUr6v1CwG/view?usp=sharing
> 
> _Originally posted by @RRosio in https://github.com/jupyterlab/jupyterlab/issues/17000#issuecomment-2504498174_

> This confirms that the part where an error is thrown an rendering is interrupted is fixed, but suggests that for very long cells which use estimated heights the rendering range may be incorrect.
> 
> _Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/17000#issuecomment-2504527418_

> I am unable to reproduce this reliably locally. It seems to be a Heisenbug.
>
> I think I caught it once and then the debugging was hinting at [..] the `scrollOffset` being set incorrectly (thus the rendering range was not updated correctly). [...]
> 
> Ideally we would be able to write a galata test reproducing the problematic behaviour.
>
> _Originally posted by @krassowski in https://github.com/jupyterlab/jupyterlab/issues/17000#issuecomment-2507634015_

**Comment by paulmromer** [comment]
I am seeing an issue that may or may not be related to "disappearing cells." Feel free to move this report if it belongs elsewhere. 

Here is what's similar. One error alone does not affect the display of the notebook, but as more errors accumulate, the notebook stops displaying correctly. Cells disappear. 

But the underlying error is different: "RangeError: Invalid line number 12 in 11-line document". 

![error](https://github.com/user-attachments/assets/48bbc52b-4fce-4c18-b043-97b29592ce2d)

I have been able to replicate this using: 
- macOS 15.1.1
- Python 3.13.0
- a requirements.txt file with these lines: 

```
jupyterlab-lsp
python-lsp-server[pycodestyle]
pyflakes
jupyterlab==4.3.2
```

Here is the notebook that I used (with a .json extension):

[reproduce_error.json](https://github.com/user-attachments/files/18025934/reproduce_error.json)

It has a cell with some lines for a function definition that is commented out because it had some errors, followed by a new definition with a new name:  

```
# def add_blank(line):
#     line_pattern = re.compile(r'( *<.*>)<a href="(.*?)">(.*)')
#     m = line_pattern.match(line)
#     if m:
#         rel_link = m.group(2)
#         link = rel_link + '" target="_blank"'
#         new_line = m.group(1) + '<a href="' + link + '>' + m.group(3)
#     else:
#         new_line = line
#     return new_line

def insert_full_link(line):
    lp = re.compile(r'( *<.*>)<a href="(.*)">(.*)')
    m = lp.match(line)
    if m:
        rel_link = m.group(2)
        full_link = rel_link + '" target="_blank'
        new_line = m.group(1) + '<a href="' + full_link + '">' + m.group(3)
    else:
        new_line = line
    return new_line

```
The blank line at the end is important. With the specified requirements.txt file, I get an indication from pycodestyle that there is a style problem on the last line. If I hover over it, it says "W391 blank line at the end of file". If I delete this line first, I do not get the error. 

To generate the error, I open the developer tools in Chrome and then delete the first 11 lines of the file -- the ones that are commented out and the blank line that comes after. To interpret the error message it may help to "Show lines" from the View menu. 

The notebook display is unaffected by this one error. Based on work in larger files where I'm doing a lot of editing, it seems to take quite a bit of elapsed time and/or additional work in the file to make cells in the notebook disappear. I do not know whether the warnings that also accumulate contribute to the problem or if it is only the errors that matter.

I've attached a screen capture that shows the state when I first open the notebook and the deletion that causes the error. It also shows an additional error that shows up when I try to save the notebook with a new name. Despite the error message, the file is saved with the new name. 

https://github.com/user-attachments/assets/2a6a359b-cac1-477e-9f00-a15088cc89b9

**Comment by krassowski** [comment]
> But the underlying error is different: "RangeError: Invalid line number 12 in 11-line document".

This is unrelated and harmless. It comes from jupyter-lsp/diagnostics highlighting logic. Thank you for providing detailed reproduction steps, I will open an issue in the relevant repository.

>  One error alone does not affect the display of the notebook, but as more errors accumulate, the notebook stops displaying correctly. Cells disappear

It looks like you are experiencing this issue, but I suspect the correlation with the accumulation of LSP errors mentioned is just a correlation because we saw the disappearing cells issue without LSP too. The next step for us is to get a reliable reproducer - if you happen to have a notebook where it happens reliably (and are able to share after redacting sensitive information), that would be super helpful.

**Comment by admin-romer** [comment]
Understood. I'll try to get a workbook where I can reproduce the failure to render.

**Comment by paulmromer** [comment]
Understood. I'll try to figure out how to reproduce the failure to render.

**Comment by yashali** [comment]
Any updates on this issue please?

**Comment by krassowski** [comment]
Thanks for bumping it - no updates so far, unfortunately this issue requires a lot of dedicated time given the complexity of the logic and that it cannot be consistently reproduced. Maybe some of the changes from https://github.com/jupyterlab/jupyterlab/pull/17132 could help here as well but its too early to tell.

**Comment by AnonymousCoward128746** [comment]
I'm experiencing either this issue or something very close to it. When I have a cell with very long output for which I disabled scrolling (after I clicked show more output), if I run the cell again (which causes no output because changed state) the non-visible parts of the notebook become blanked.

I have a hunch this bug is related to the "lazy scrolling" feature of the notebook: If you quickly drag the scroll bar to another section of the documents, it takes a few moments for the cells to re-render, most likely as a performance optimization. 

In the case I described, it looks a lot like the scroll logic is somehow stuck, so that even if you move to another part of the document, the cells do not get rendered. Running any **other** cell clears the issue and the rest of the notebook then renders properly again when scrolling to it.

This is with `notebook-7.3.0, jupyterlab-4.3.4`, and I've reproduced it multiple times with a notebook I'm working on (which I can't share). I cannot reproduce it 100% reliably, but usually within 2-3 attempts.

With `notebook-7.2.3, jupyterlab-4.2.7` I've not been able to reproduce this issue even once.

**Comment by abudissu** [comment]
Hey everyone,

I've encountered the same bug and my workaround for the moment is to create a new cell, which seems to make all the other cells on the screen to render properly.

I'll try to create a minimal reproducible example, but as others have already mentioned it seems to be linked to cells with very long output.

**Comment by AnonymousCoward128746** [comment]
This is just to say that after being forced to downgrade a minor version because this bug is still there, I've now gone ahead and downgraded even further to notebook 6, because common keyboard shortcuts cannot be assigned with notebook 7. At least, I can't figure out how to do it with the awkward new settings editor.

Isn't it weird that I keep having to move to older and older versions to get a better experience? 🤔

**Comment by krassowski** [comment]
@AnonymousCoward128746 

You should be able to use Notebook 7:
- this issue should be fixed by switching Settings → Settings Editor → Notebook → Windowing Mode → "defer"
- to add shortcuts you can got to Settings → Settings Editor → JSON Settings Editor → Keyboard Shortcuts. The UI shortcuts editor indeed does not support adding shortcuts for commands which do not have an existing shortcut. This is tracked in https://github.com/jupyterlab/jupyterlab/issues/13705 and there was a draft PR but it is not being actively worked on by anyone as far as I am aware https://github.com/jupyterlab/jupyterlab/pull/14015

> Isn't it weird that I keep having to move to older and older versions to get a better experience? 🤔

Yes, sometimes it is like this but it should not be. You are right.

> awkward new settings editor

If something specific is awkward please open a bug report describing it and suggesting how to make it less awkward.

**Comment by AnonymousCoward128746** [comment]
@krassowski, thank you for the helpful update.

Is "Windowing Mode/Defer" a fix or a workaround? it sounds like turning off an optimization, which might hurt usability in heavy notebooks. Is this correct? Is there a plan to change the defaults?

Notebook 6 had an easy, discoverable way to edit shortcuts which is vitally important for productivity. This was a big regression in NB7, which you yourself reported in Jan 2023 (two years ago), but is still not resolved. I'm guessing NB7 requires me to manually edit config files to achieve same? 

I have great respect for "PRs welcome" and this is open-source. But Jupyter pushing forward with ever more features and two years of new versions without addressing major regressions to functionality suggests an issue with project focus.

That said, the Jupyter Project (or you) owe me precisely nothing.

**Comment by krassowski** [comment]
> Is "Windowing Mode/Defer" a fix or a workaround? it sounds like turning off an optimization, which might hurt usability in heavy notebooks. Is this correct?

Yes, that's correct.

> run all cells above

also see comments in https://github.com/jupyterlab/jupyterlab/issues/6422

**Comment by krassowski** [comment]
I think it happend after clicking on a ToC to scroll to an item. It might be one way to trigger the bug.

**Comment by AnonymousCoward128746** [comment]
@krassowski, If I manage to bisect this to a particular commit will you be able to follow this up towards a resolution?

**Comment by oakif** [comment]
I found out how to duplicate this myself: open a notebook, select the outside of a cell, keep "B" pressed (to create a lot of new cells), and then after a few seconds scroll up. The rest of the notebook will show up blank.

**Comment by celestinoxp** [comment]
It seems that the problem has been discovered and partially fixed, but even after the updates the problem is still not resolved. ;(
Please fix it!

**Comment by ogencoglu** [comment]
This happens in `jupyterlab==4.4.0` on chrome even if the outputs are cleaned. So it is not a large output issue.

**Comment by matt-loft** [comment]
Experiencing the same issue in Chrome with `jupyterlab==4.2.4`. Able to reproduce by copying a cell, clicking out, and pasting a few times with `v`.

**Comment by ogencoglu** [comment]
There are actually 2 separate issues:
- some cells or some of their parts not rendering randomly
- scrolling suddenly jumping some cells completely

**Comment by krassowski** [comment]
>  or some of their parts not rendering randomly

This is tracked in https://github.com/jupyterlab/jupyterlab/issues/17507 and should be fixed soon

**Comment by wkvolkman** [comment]
Hum, this happens 100% of the time with all of my notebooks, annoying as heck, just upgraded to 4.4.2 and no change.  I'm using the latest Chrome on Macbook as my display, server is a Linux VM.  Like I said it happens 100% of the time, however I have cells with 30 to 30 k lines of output so YMMV.

**Comment by dstoppacher** [comment]
Hello, thanks for making the effort to fix the issue. I am in the same situation as @wkvolkman. I use large notebooks in Firefox under the latest Fedora, and working with them has become almost impossible.

**Comment by Hnasar** [comment]
@krassowski seems like this one can be closed and is fixed already?
> This is tracked in https://github.com/jupyterlab/jupyterlab/issues/17507 and should be fixed soon

**Comment by krassowski** [comment]
No, there were two issues:
- (a) lines not rendering on scroll
- (b) cells not rendering on scroll

(a) was fixed by https://github.com/jupyterlab/jupyterlab/pull/17528 in JupyterLab `v4.4.2`. (b) was not fixed yet and has a root cause in a different component altogether.

**Comment by wkvolkman** [comment]
Over the weekend I upgraded to 4.4.3 and it seems better although I've encountered a plethora of errors in the other extensions that I had installed.

**Comment by johann-petrak** [comment]
I keep seeing weird and erratic behavior in practically all Jupyter lab (Python) notebooks whenever they contain more than just a few cells and have some slightly more complex stuff in them, e.g. Bokeh plots. 

When scrolling, the notebooks sometimes looks completely empty, sometimes the output of a cell (e.g. a Bokeh plot)  just disappears and never comes back again, sometimes that content gets rendered after a while. The opposite is also possible: scrolling back and forth between two position in the notebook may show the cell output, until, just after some more continued scrolling, the output of one of those cells is not visible any more. 
Scrolling may refuse to stop at a specific position in the notebook and always either jump to before or after where I want to scroll to.

With all that there are no errors on the Javascript console. 

Versions I am using: 

* jupyter                   1.1.1
* jupyter_bokeh             4.0.5
* jupyter_client            8.6.3
* jupyter-console           6.6.3
* jupyter_core              5.8.1
* jupyter-events            0.12.0
* jupyter-lsp               2.2.5
* jupyter_server            2.16.0
* jupyter_server_terminals  0.5.3
* jupyterlab                4.4.3
* jupyterlab_pygments       0.3.0
* jupyterlab_server         2.27.3
* jupyterlab_widgets        3.0.15
* notebook 7.4.3 
* IPython 9.2.0 
* bokeh 3.7.3
* BokehJS 3.7.3 


For what it is worth, here is a recording that shows the behavior with Bokeh plots. I have no idea if this is a bokeh problem or a jupyter lab problem (sorry for the weird aspect ratio). This video shows how I create the plots, then scroll between them with the first one disappearing and not coming back, then later disappearing and coming back by itself. 

https://github.com/user-attachments/assets/55b6a0ce-96ac-44ab-b054-f65a8e2b7236

**Comment by johann-petrak** [comment]
This is actually even worse, at times the notebooks just shows utterly empty space before or after a few visible cells, right up to the beginning or end. While nothing is shown it still occupies vertical space and can be scrolled. Nothing showing up on the JS console. 
Reloading the whole web page brings back those cells. 
I feel the notebook in the current version has so many annoying problems that it is not really a version that should have been released. 
Does anyone know what the most recent version is that is still working properly?

**Comment by paulmromer** [comment]
I have some notebooks where this problem still shows up.  I find that going to Advanced Settings and changing the Notebook Windowing mode to "defer" generally makes the problem go away for me. I haven't test for a change in performance. In day to day use, I do not perceive a difference. Of course, your mileage may vary. 

To be more precise, my default setting is "full" instead of "defer." I switch to "defer" if I run into problems. But I reset all my settings back to my preferred defaults when I restart JL. This way, I stay aware about whether this is still an issue.

**Comment by ag1988** [comment]
@johann-petrak [3.6.8](https://github.com/jupyterlab/jupyterlab/releases/tag/v3.6.8)

**Comment by johann-petrak** [comment]
3.6.8 as the version of jupyter lab? That is a very, very old version. 
I do not think that would allow the other packages I need (like bokeh, plotly, jupyter widgets, panel) to work  :/

**Comment by johann-petrak** [comment]
> I have some notebooks where this problem still shows up. I find that going to Advanced Settings and changing the Notebook Windowing mode to "defer" generally makes the problem go away for me. I haven't test for a change in performance. In day to day use, I do not perceive a difference. Of course, your mileage may vary.
> 
> To be more precise, my default setting is "full" instead of "defer." I switch to "defer" if I run into problems. But I reset all my settings back to my preferred defaults when I restart JL. This way, I stay aware about whether this is still an issue.

I just tried this with most recent Jupyterlab version 4.4.4 and I can confirm that changing the "Windowing mode" setting from the default "full" to either "defer" or "none" seems to make the problem go away. 
Since the "full" setting often causes the cell output (in my case, a bokeh plot) to NEVER render again, I would think that this can be considered a bug which must get fixed. 
At least for now, the default should get changed to defer or none because finding this workaround is time consuming and annoying if one is just confronted with the weird, random symptoms.

**Comment by CrafterKolyan** [comment]
Cells on top of notebook also wouldn't render on certain conditions.
Also I was able to make 100% reproduction.

## Reproduce

1. `pip install -U pillow` (in my case `pillow==11.3.0`)
2. Open [reproduce-rendering-bug.ipynb](https://github.com/user-attachments/files/22197112/reproduce-rendering-bug.ipynb)
3. Execute with Shift+Enter first **5** cells (last cell that you execute should be the cell that gives you image with multiple circles)
4. Scroll more to top so you would see small part of 2nd cell, 3rd cell and 4th cell (**do not scroll to very top of notebook**)
5. Execute with Shift+Enter cell 4 (you will see exception in Python)
6. Execute with Shift+Enter cells 2, 3, 4 (you should be at the bottom of output of cell 4)
7. Go to the top of notebook
8. Observe that top 2 cells of the notebook are no longer rendered.

Video reproduction:
https://github.com/user-attachments/assets/4929180b-a4f8-41ad-ab59-8ddc20a224b4

## Expected behavior

Cells on top of notebook should render

## Context

Jupyterlab: 4.4.7
Pillow: 11.3.0
Browser: Chrome 140.0.7339.81 or Firefox 142.0.1

**Comment by dylanpulver** [comment]
I got a deterministic reproduction of the `full`-windowing case and traced it. It is not a bad range computation — the `WindowedList` stops listening to scroll altogether, because a latch is never released.

## Mechanism

`WindowedList.scrollTo()` sets `_scrollUpdateWasRequested = true` and requests an update. That flag is only ever cleared inside `_update()`, and the clearing sits inside the `newWindowIndex !== null` branch:

```ts
const newWindowIndex = this.viewModel.getRangeToRender();
if (newWindowIndex !== null) {
  ...
    // Update scroll
    if (this._scrollUpdateWasRequested) {
      this._outerElement.scrollTop = this.viewModel.scrollOffset;
      this._scrollUpdateWasRequested = false;
    }
}
```

On 4.4.x, `getRangeToRender()` returns `null` when the window is unchanged. So when a programmatic scroll lands inside the **same** rendered window, `_update()` returns early and the flag stays `true` forever. After that, the `!this._scrollUpdateWasRequested` guard in `onScroll()` rejects every user scroll: `viewModel.scrollOffset` freezes, `_update()` and `_updateTotalSize()` never run again, and the viewport stays at whatever `translateY()` it last had. That stale translate is the blank area.

## Evidence

JupyterLab 4.4.7, `windowingMode: full`, Chrome 151 / macOS, using the notebook and steps from @CrafterKolyan's 100%-reproduction report above, with `WindowedList` / `WindowedListModel` prototype methods wrapped in the running app to log calls and state. 3 of 3 attempts reproduced. Final state, scrolled to the very top:

```
real scrollTop        = 0        viewModel.scrollOffset = 3401.2
viewport transform    = translateY(567.656px)   (stale)
inner element height  = 4066.75px               (correct total: 6277.34px)
cells 0 and 1         = display:none
_scrollUpdateWasRequested = true
getRangeToRender() returned null 14 times out of 36 calls
no uncaught exceptions
```

Setting `_scrollUpdateWasRequested = false` from the console and changing nothing else instantly restores everything: cells 0 and 1 reappear, the inner height corrects to 6277.34px, and scrolling tracks again.

It also explains two things already reported in this thread:

- ["create a new cell, which seems to make all the other cells render properly"](https://github.com/jupyterlab/jupyterlab/issues/17023#issuecomment-2594736669) — inserting a cell changes `widgetCount`, so the range differs, `getRangeToRender()` is non-null, `_update()` runs its body and clears the flag. I checked this: the flag flips to `false` on the insert and the notebook recovers.
- `defer` / `none` avoid it because `scrollTo()` returns before setting the flag when windowing is inactive.

## Status on `main`

I could **not** reproduce it on 4.6.3 with `windowingMode: full`: `getRangeToRender()` returned null 0 times out of 35 calls. #17904 changed `return null` to `return newWindowIndex ?? null`, which is never nullish, so the early return in `_update()` is now dead code. That looks incidental to the minimap work rather than deliberate. 4.4.x still has `return null` as of v4.4.10.

So the latch is unreachable on `main` today, but still structurally present: the clear is nested in `if (newWindowIndex !== null)`, and the doc comment still advertises that the method returns `null` when the range does not need updating. Reinstating that fast path as an optimisation would silently bring back a permanently frozen notebook. Hoisting the `_scrollUpdateWasRequested` handling out of that branch would make it unreachable by construction. Happy to open that, and/or a 4.4.x backport, if either is wanted.

**Not verified:** that this is the only mechanism behind every report in this thread; the `contentVisibility` path; 4.5.x; browsers other than Chrome.

<sub>Disclosure: this investigation was AI-assisted. The reproductions, traces and measurements quoted above are from the instrumented runs described.</sub>
