### ISSUE TITLE
Workspace interface behavior unclear

### ISSUE THREAD

**Issue by joshjob42** [jupyterlab/jupyterlab#3673]
Hello all,

I don't know where else to ask this, so I thought I'd create a new issue, and if I'm being stupid and this is easy it'll be closed quickly.

As far as I understand, if I navigate to /lab/workspaces/<workspace_name> either workspace <workspace_name> will be loaded from memory and opened or a new workspace will be created. I assume that the new workspace that opens should open with just the launcher, however it seems currently to duplicate the workspace I already have open in another tab.

Moreover, if I close a tab in one workspace (say a notebook, console, editor, etc...), let's call it <primary>, and then reload the browser page for another workspace, say <secondary>, the change in <primary> is reflected in <secondary> and vice versa. That is, not only does navigating to <secondary> lead me to a page with the same layout as <primary> when opening from a fresh JupyterLab session, the two seem to remain connected at all times. It doesn't appear there's any workspaces being made at all, just a single view on one underlying workspace that can be viewed in diverging ways in different browser tabs only for as long as each respective browser tab is open and hasn't been reloaded.

Is this the expected behavior? ie workspaces aren't semi-permanent (so long at least as the underlying JupyterLab process is running), but just different temporary views? Or am I experiencing an actual issue? From #3490 it appears that it's meant to be closer to semi-permanent, reloadable, etc. I realize workspaces aren't prominently displayed at the moment, but I'm eager to use them to separate different projects I'm currently working on, so any help would be most appreciated.

**Comment by jasongrout** [comment]
IIRC, a creating a new workspace will take your existing state as the starting state. That way you can set up things how you want, then go to the workspace URL to snapshot it. Or you can easily fork another workspace by just changing the workspace name.

Do you have jupyterlab open in two browser tabs? There may be some conflict going on in the storage for a workspace. Can you try your experiments with just one browser tab?

**Comment by joshjob42** [comment]
Yes I was using JupyterLab in two browser tabs, as I assumed part of the value of workspaces was to have different views open at once.

I tried again, shutting down my instance of Lab, restarting it, and set up a configuration. Then I went to workspaces/primary in the same browser tab and it copied the configuration as expected. I then navigated to workspaces/secondary, again in the same tab, and modified the configuration. After that, navigating back to both main and /primary I saw the changes I'd made in the /secondary workspace, all in the same browser tab.

That's not the expected behavior, right? It does seem like somehow there's a storage conflict going on, though it doesn't make much sense to me why.

**Comment by afshin** [comment]
JupyterLab is not really currently designed in a way that makes working in multiple tabs predictable because the "working memory" of your application state is `window.localStorage`, which means that the state will be shared by multiple tabs. This is why you're seeing seemingly unpredictable results when you have multiple tabs open. We have had some conversations about launching native windows that have a child/parent relationship with each other, but the main model of user interaction with JupyterLab is within a single window/tab.

If you go to workspace that does not exist, its starting point is your current state as it exists in local storage.

**Comment by afshin** [comment]
Currently, if you have a need that can only be addressed by multiple windows, you can open two different browsers or you can have one incognito window and one non-incognito window. If they use the same workspace URL, then each new thing you do in one window will clobber what the other window had saved and since saves have no way of "notifying", you will have unexpected results. So to truly have two different views, you'd need to use different workspace URLs (or no workspaces at all).

**Comment by jasongrout** [comment]
Another option is to use separate Firefox tab containers to separate different local storages.

**Comment by joshjob42** [comment]
Well I guess I don't *need* multiple windows, but it'd be nice. However, as I mentioned in my last post this isn't just when I have multiple tabs open. Even when I use a single tab and navigate between workspaces I still get this clobbering behavior.

Can someone else open up a JupyterLab instance, set it up, then navigate to a new workspace name, change the configuration, and then go back and see if the original workspace has now been changed? I don't need multiple windows to get this clobbering behavior, I just have to switch from one workspace to another serially in a single browser tab.

**Comment by jasongrout** [comment]
1. I agree it would be great to get it working in multiple tabs

2. I'll test the single-tab version for you. I thought I did a while ago and it worked great. Are you on jlab 0.31.1?

**Comment by joshjob42** [comment]
Yes I am. Thank you very much for your help!

**Comment by afshin** [comment]
@joshjob42 @jasongrout I see this behavior in my current build. I wonder if we have a regression. I'll look into it.

**Comment by afshin** [comment]
Okay, I see. This behavior actually *is* working as intended. The only thing to consider is that there is a debounce interval (`WORKSPACE_SAVE_DEBOUNCE_INTERVAL`) that basically waits for `two seconds` before saving your workspace after you've made modification, the idea being to not flood the server with workspace requests.

So if you look at the screencap below, the behavior works as intended as long as I wait two seconds after modifying my workspace.

![workspaces](https://user-images.githubusercontent.com/159529/35195970-82755e9e-fec3-11e7-9f7a-bcc771e23974.gif)

**Comment by joshjob42** [comment]
I'm not sure how you did that behavior, but I waited for quite a long time and still get the clobbering behavior. Here's a link where you can watch my screencapture of it. https://drive.google.com/file/d/19MGEW1utzECbhqQrE23i-rqhbpYi7TWS/view

**Comment by afshin** [comment]
@joshjob42 I'm sorry, but I can't understand exactly what's going on in your session because the URL bar is not showing. I will try this behavior not using my current build, which is based off of the latest `master` branch and does have some updates to the areas of code that affect this behavior.

It may turn out to be the case that the behavior in the current development branch that will soon be released is different than the last release.

**Comment by mehd-io** [comment]
Hi @afshin , any update on this issue? I tried with the latest version (0.31.8) with only one tab and couldn't reproduce the behaviour as you showed. When I come back to a previous created workspaces, it just copied again from the current one.
![jupyterlab_workspace4](https://user-images.githubusercontent.com/19834862/36645641-32905cf2-1a6c-11e8-9072-56d30e7d71e2.gif)

**Comment by joshjob42** [comment]
I couldn't for the life of me figure out how to do that sort of gif video capture so thank you @mehd-io . I just wanted to chime in and say that I'm also still observing this behavior even with the latest JupyterLab release. "Workspaces" just don't see to separate even when you only access them sequentially in a single tab and wait for arbitrary time periods (much longer than two seconds) between modifying the workspace and switching to a different one. They still just clobber each other no matter what I do as far as I can tell.

**Comment by afshin** [comment]
@joshjob42 The behavior you captured is indeed incorrect. I think I know what is happening: there was a bug in an earlier version of `jupyterlab_launcher` that basically meant it was not saving workspaces if a workspaces folder did not exist on your system. That bug has been fixed. So if you upgrade your version of `jupyterlab_launcher`, that should resolve this issue.

On the larger issue of multiple windows, we are targeting it for 1.0.

cf. https://github.com/jupyterlab/jupyterlab/pull/4041

**Comment by mehd-io** [comment]
@afshin , so I've just upgraded the jupyterlab_launcher and still got exactly the same behaviour as showed above, under jupyter 0.31.8.

**Comment by afshin** [comment]
Can you open your browser's developer tools and see if there are any errors in your JS console?

**Comment by afshin** [comment]
Fixed in https://github.com/jupyterlab/jupyterlab/pull/4708
