### ISSUE TITLE
Cannot open a directory with name "checkpoints"

### ISSUE THREAD

**Issue by qwfy** [jupyterlab/jupyterlab#4099]
If there is a directory with the name "checkpoints", double click on it (in the "Files" tab on the "Left Area") will result an error, clicking on directory with other names behaves correctly:

![screenshot](https://user-images.githubusercontent.com/11158705/36941856-b5df6b56-1f9f-11e8-94eb-0d9fedb4bf56.png)

```
$ jupyter --version
4.4.0

$ jupyter lab --version
0.32.0.dev0
```

**Comment by blink1073** [comment]
Thanks for the report!  In classic notebook we get a JS console error instead: `TypeError: list.content is undefined`.

**Comment by jtpio** [comment]
It looks like the notebook api has a `/api/contents/{path}/checkpoints` endpoint, which might be conflicting with the directory being part of the url (at least for the classic notebook):

- https://github.com/jupyter/notebook/blob/02d6cd55b39de287b9961cd394895ac6a86acaab/notebook/services/api/api.yaml#L257
- https://github.com/jupyter/notebook/blob/ca50f1af5afb525fd95b98b2e61e69db28094467/notebook/static/services/contents.js#L221

**Comment by hlb** [comment]
do we have a plan to fix this issue? :)

**Comment by vidartf** [comment]
I think this should probably be opened as an issue on the notebook repo (preferably linking back here).

**Comment by karray** [comment]
Same here
```
jupyter --version
4.4.0

jupyter lab --version
0.35.6
```

**Comment by jasongrout** [comment]
As mentioned above, this is a notebook server issue and should be solved in https://github.com/jupyter/notebook/

**Comment by ManuelZ** [comment]
I have just been wandering around my code for one hour to figure out why when I click in my "checkpoints" directory I end up in the same spot that I was before clicking.

**Comment by gogobd** [comment]
Same here:
# jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.14.0
ipykernel        : 5.2.1
jupyter client   : 6.1.3
jupyter lab      : 2.1.2
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.6
traitlets        : 4.3.3

**Comment by mehdirezaie** [comment]
same with 6.0.3

**Comment by ericspod** [comment]
I'm still experiencing this issue as well on Ubuntu 16.04

jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : 4.7.1
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.1.0
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3

**Comment by vidartf** [comment]
This issue is not with JupyterLab, but with https://github.com/jupyter/notebook/ . Please submit an issue there if you want this to be resolved.
