### ISSUE TITLE
Unexpected scrolling with `"rulers"` on

### ISSUE THREAD

**Issue by jiafengkevinchen** [jupyterlab/jupyterlab#6836]
When I turn on the `ruler` option in Settings/Notebook, say `"ruler" : [88]`, code cell would be a little scrollable:
![jitter](https://user-images.githubusercontent.com/24930289/61262879-f752c900-a754-11e9-851a-eb644a89bcaa.gif)

- OS: macOS 10.14.5
- Browser: Chrome 75
- JupyterLab 1.0.2

**Comment by ian-r-rose** [comment]
Good catch @jiafengkevinchen! On my machine it's *very* subtle, but there. Seems like a CSS issue, but it was not obvious to me how to fix it.

**Comment by t-makaro** [comment]
Related notebook [issue](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1149).

I found that using chrome's dev tools to change the ```.CodeMirror-rulers``` css class's ```bottom: -20px``` property to ```bottom: 0``` fixes this in chrome 75 (for both classic notebook and lab). I don't know where to go with this information, but I hope it helps.

**Comment by ian-r-rose** [comment]
Thanks for the cross reference @t-makaro

**Comment by t-makaro** [comment]
I submitted a [fix](https://github.com/codemirror/CodeMirror/pull/5950) to codemirror. A release of codemirror along with Jupyter lab updating to the latest version should fix the issue.

**Comment by jasongrout** [comment]
> I submitted a [fix](https://github.com/codemirror/CodeMirror/pull/5950) to codemirror. A release of codemirror along with Jupyter lab updating to the latest version should fix the issue.

Thanks for pushing this all the way to a fix upstream!

**Comment by t-makaro** [comment]
@nubtwo Someone still has to submit a PR to update codemirror to >5.48.4 like #6321.

**Comment by mc51** [comment]
I still experience this with the latest version, i.e. 1.1.5 
It's really frustrating, because scrolling through a notebook does not work properly anymore. The scrolling will keep "hanging" in code-cells. No way to smoothly scroll anymore.

**Comment by jasongrout** [comment]
This is fixed in the soon-to-be-released JupyterLab 2.0.
