### ISSUE TITLE
Favicons not found

### ISSUE THREAD

**Issue by tjcrone** [jupyterlab/jupyterlab#9355]
## Description

My favicons are being served from /static (e.g. http://10.0.1.66:8888/static/favicon.ico), but I get 404s on /static/favicons: `404 GET /static/favicons/favicon.ico (10.0.1.46) 74.27ms referer=http://10.0.1.66:8888/lab?` Is there a problem with the templates or am I doing something wrong? Thanks!

## Reproduce

Start server and watch logs.

## Expected behavior

That we would not get 404s on the favicons.

## Context

- Operating System and version: Debian 10
- Browser and version: Chrome
- JupyterLab version: 3.0.0rc7

<details><summary>Troubleshoot Output</summary>
<pre>
(venv) debian@beaglebone:~$ jupyter troubleshoot
$PATH:
	/home/debian/venv/bin
	/usr/local/bin
	/usr/bin
	/bin
	/usr/local/games
	/usr/games

sys.path:
	/home/debian/venv/bin
	/usr/lib/python37.zip
	/usr/lib/python3.7
	/usr/lib/python3.7/lib-dynload
	/home/debian/venv/lib/python3.7/site-packages

sys.executable:
	/home/debian/venv/bin/python

sys.version:
	3.7.3 (default, Jul 25 2020, 13:03:44) 
	[GCC 8.3.0]

platform.platform():
	Linux-4.19.94-ti-r50-armv7l-with-debian-10.5

which -a jupyter:
	/home/debian/venv/bin/jupyter

pip list:
	Package             Version  
	------------------- ---------
	Adafruit-BBIO       1.2.0    
	argon2-cffi         20.1.0   
	async-generator     1.10     
	attrs               20.3.0   
	Babel               2.9.0    
	backcall            0.2.0    
	bleach              3.2.1    
	certifi             2020.11.8
	cffi                1.14.3   
	chardet             3.0.4    
	cycler              0.10.0   
	decorator           4.4.2    
	defusedxml          0.7.0rc1 
	entrypoints         0.3      
	idna                2.10     
	importlib-metadata  2.0.0    
	ipykernel           5.3.4    
	ipython             7.19.0   
	ipython-genutils    0.2.0    
	ipywidgets          7.5.1    
	jedi                0.17.2   
	Jinja2              3.0.0a1  
	json5               0.9.5    
	jsonschema          3.2.0    
	jupyter-client      6.1.7    
	jupyter-core        4.7.0rc0 
	jupyter-server      1.0.5    
	jupyterlab          3.0.0rc7 
	jupyterlab-pygments 0.1.2    
	jupyterlab-server   2.0.0rc2 
	jupyterlab-widgets  1.0.0a6  
	kiwisolver          1.3.1    
	MarkupSafe          2.0.0a1  
	matplotlib          3.3.3    
	mistune             0.8.4    
	nbclassic           0.2.3    
	nbclient            0.5.1    
	nbconvert           6.0.7    
	nbformat            5.0.8    
	nest-asyncio        1.4.3    
	notebook            6.1.5    
	numpy               1.19.4   
	packaging           20.4     
	pandas              1.1.4    
	pandocfilters       1.4.3    
	parso               0.7.1    
	pexpect             4.8.0    
	pickleshare         0.7.5    
	Pillow              8.0.1    
	pip                 18.1     
	pkg-resources       0.0.0    
	prometheus-client   0.8.0    
	prompt-toolkit      3.0.8    
	ptyprocess          0.6.0    
	pycparser           2.20     
	Pygments            2.7.2    
	pyparsing           3.0.0b1  
	pyrsistent          0.17.3   
	python-dateutil     2.8.1    
	pytz                2020.4   
	pyzmq               19.0.2   
	requests            2.25.0   
	Send2Trash          1.6.0b1  
	setuptools          40.8.0   
	six                 1.15.0   
	terminado           0.9.1    
	testpath            0.4.4    
	tornado             6.1      
	traitlets           5.0.5    
	urllib3             1.26.1   
	wcwidth             0.2.5    
	webencodings        0.5.1    
	widgetsnbextension  3.5.1    
	xarray              0.16.1   
	zipp                3.4.0
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by tjcrone** [comment]
Hmm. I restarted and the favicon.ico 404s went away, but the busy favicon 404s continue:
```
[W 2020-11-17 18:33:18.668 ServerApp] 404 GET /static/favicons/favicon-busy-1.ico (10.0.1.46) 158.93ms referer=http://10.0.1.66:8888/lab?
```

The favicon.ico is located in a few places, including `/jupyter_server/static/` , but the busy icons are only in `notebook/static/base/images/`:
```
(venv) debian@beaglebone:~$ find $PWD | grep favicon.ico
/home/debian/venv/lib/python3.7/site-packages/jupyter_server/static/favicon.ico
/home/debian/venv/lib/python3.7/site-packages/notebook/static/favicon.ico
/home/debian/venv/lib/python3.7/site-packages/notebook/static/base/images/favicon.ico
```
```
(venv) debian@beaglebone:~$ find . | grep favicon-busy
./venv/lib/python3.7/site-packages/notebook/static/base/images/favicon-busy-1.ico
./venv/lib/python3.7/site-packages/notebook/static/base/images/favicon-busy-3.ico
./venv/lib/python3.7/site-packages/notebook/static/base/images/favicon-busy-2.ico
```
I'm almost certainly doing something wrong. But I copied the busy icons into `/jupyter_server/static/` and the 404s went away. Hmm.

**Comment by tjcrone** [comment]
It seems like the original 404 went away because Chrome cached the favicon, which it found while I was poking around, because when I cleared the favicon cache the error came back. I created a new directory and copied all of the ICO files into 
/jupyter_server/static/favicons/ and all the favicon 404s went away. I'm thinking that the files are not in the right place or the templates are off in rc7. Thanks and good luck!!

**Comment by tjcrone** [comment]
Closing because I think this likely belongs in https://github.com/jupyter/jupyter_server. Sorry to bother.  Current work-around is to copy all the favicons from `notebook/static/base/images/` into `/jupyter_server/static/favicons/`. Thanks Jupyterlab!!

**Comment by jasongrout** [comment]
Do you have a link to the issue in Jupyter Server, for reference?

**Comment by tjcrone** [comment]
@jasongrout, I didn't open an issue there because after closing this, I started to doubt whether belongs in jupyter_server or maybe somewhere else, such as jupyter/jupyter. But I don't really know. It can be difficult to know which repo to connect with for a project with this many related orgs and repos. Also not sure that it's not just my setup, which is always a possibility. If you would like me to post this issue elsewhere please let me know. Thanks!

**Comment by jasongrout** [comment]
We just realized that jupyter_server was accidentally not bundling the favicons. This is now fixed in Jupyter Server 1.0.7.

Do you want to check that if installing Jupyter Server 1.0.7 fixes things?

**Comment by tjcrone** [comment]
Oh I'm glad you figured this out! I am deploying on a SBC from scratch using a script, so this is the sort of thing that might be easier to find under such circumstances. I will try 1.0.7 and let you know if any issues remain. Cheers and thank you Jupyterlab!
