### ISSUE TITLE
The autocomplete does not work when I press Tab or Shift + Tab

### ISSUE THREAD

**Issue by khalidme94** [jupyterlab/jupyterlab#9602]
## Description

As Written in the title the autocomplete does not work with me, I used to use it in the previous version of jupyter notebook but now I am using the latest version (3) , and it does not work even in the jupyter lab.

**Comment by piersoh** [comment]
This also seems to be an issue in the code console in Jupyterlab

**Comment by BradleyKirton** [comment]
Hi there, same issue here.

I get the following error message in the logs.

```TypeError: __init__() got an unexpected keyword argument 'column'```

Looks like column is being passed to `jedi.Interpreter` within the IPython/core/completer.py module.

**Comment by khalidme94** [comment]
for me I don't get any error, but the command is not auto-completed

**Comment by moltaire** [comment]
I have the same error in jupyterlab Version 3.0.3, installed from conda-forge.
Shift + Tab still shows a floating documentation panel, but autocomplete for modules or function does not show and posts the error to my command line.

**Comment by PKUliubaojian** [comment]
for me, the following command works:
`conda install jedi=0.17`

**Comment by BradleyKirton** [comment]
Just an update, I see there is an open issue [12763](https://github.com/ipython/ipython/issues/12763) on the ipython repo.

They link this fix [12740](https://github.com/ipython/ipython/issues/12740).

**Comment by krassowski** [comment]
This was fixed in IPython 7.20. You can upgrade IPython using:

pip install -U "ipython>=7.20"

I will be close this issue as it is not a bug in JupyterLab but rather a temporary incompatibility between Jedi and IPython which was already resolved. Sorry everyone that you have not got a response earlier.

**Comment by chriswininger** [comment]
> ```shell
> pip install -U "ipython>=7.20"
> ```

Sadly not an option for folks on python 3.6 as ipython 7.20 and above does not offer support of python 3.6 :crying_cat_face: 

https://github.com/ipython/ipython/issues/12821#issuecomment-806763164

**Comment by krassowski** [comment]
This is correct. In that case you can still downgrade Jedi to 0.17, but I would recommend upgrading Python instead as Python 3.6 will stop receiving security updates in 4 months time (and if there are issues that you need to work out, reluctant administrators, or dependencies that need to be pushed to upgrade it would be better to work it out now rather than after the security support ceases - for your own benefit and safety).

**Comment by rpmacaspac** [comment]
issue still exists on 'ipython_version': '7.22.0',

pd.(+tab) doesn't work but with no error
